<?php

return [
    'pageTitle' => 'Queen Batches',
    'pageSubtitle' => 'Queen batches are used on the location page to quickly add queens to their hives. On this page, you can manage sets, share them in specific locations, and follow the statistics for each batch.',
    'lineLabel' => 'Queen line',
    'confirmedLabel' => 'confirmed',
    'potentiallyBroodingLabel' => 'potentially breeding',
    'virginQueensLabel' => 'virgin queens',
    'nameLabel' => 'Batch name',
    'daysOfLifeLabel' => 'Days of life',
    'cycleLengthLabel' => 'Cycle length',
    'serieLabel' => 'Serie',
    'weeksLabel' => 'weeks',
    'soldLabel' => 'sold',
    'lostLabel' => 'lost',
    'efficiencyLabel' => 'efficiency',
    'fabAddNewTooltip' => 'Add new batch',
    'editBatchLabel' => 'Edit batch',
    'efficiencyTooltip' => 'The batch efficiency will be visible if the number of queens sold, lost and confirmed will exceed 25% of batch size.',
    'infoTitle' => 'What are queen batches used for?',
    'infoDescription' => 'Queen batches are part of the series and can easily add queens to the hives with one click. You can set up a batch for each queen line and location. Later on, you will see statistics for each batch.',
    'addSuccessMessage' => 'New batch was added successfully.',
    'deleteSuccessMessage' => 'Batch was deleted successfully.',
    'updateSuccessMessage' => 'Batch :name was updated successfully.',
    'locationShortLabel' => 'Location',
    'disposedShortLabel' => 'Disposed',
    'limitShortLabel' => 'Limit',
    'emptyHives' => 'empty hives',
];
