<?php
return [
    'homeGroupLabel' => 'Queens',
    'homeLabel' => 'Breeder Panel',
    'workLabel' => 'Work Panel',
    'locationsGroupLabel' => 'Locations',
    'locationsSummary' => 'Summary',
    'warehouseGroupLabel' => 'Warehouse',
    'warehouseHivesLabel' => 'Hives',
    'seriesLabel' => 'Queen Series',
    'batchesLabel' => 'Queen Batches',
    'breedingGroupLabel' => 'Breeding',
    'ordersGroupLabel' => 'Orders',
    'ordersLabel' => 'Summary',
    'orderClientsLabel' => 'Clients',
    'ordersDailyLabel' => 'Daily work',
    'ordersCalendarLabel' => 'Calendar',
    'ordersShippingLabel' => 'Shipments',
    'ordersSettingsLabel' => 'Orders settings',
    'ordersStatsLabel' => 'Order statistics',
    'focusModeLabel' => 'Focus mode',
    'reportsGroupLabel' => 'Reports',
    'reportsUnionsLabel' => 'Beekeeping unions',
    'settings' => [
        'general' => 'Settings',
        'account' => 'General',
        'team' => 'Team',
        'queenLines' => 'Queen Lines',
        'orders' => 'Orders',
    ]
];
