<?php
return [
    'mainPageTitle' => 'Orders list',
    'mainPageSubtitle' => 'You can manage your orders here. Removed or closed orders are displayed on the separate list.',
    'clientsPageTitle' => 'Your clients',
    'clientsPageSubtitle' => 'You can manage your client data here. All clients will be available in order section based on this list.',
    'shipmentPageTitle' => 'Shipments',
    'shipmentPageSubtitle' => 'You can manage your shipments here.',
    'settingsPageTitle' => 'Your store settings',
    'settingsPageSubtitle' => 'You can change the settings of the store module here. You can manage your products, beekeeping unions list and shipping methods.',
    'statsPageTitle' => 'Order statistics',
    'statsPageSubtitle' => 'You can check your orders statistics here',
    'settingsProductTitle' => 'Your products',
    'settingsClubsTitle' => 'Beekeeping clubs',
    'settingsUnionsTitle' => 'Beekeeping unions',
    'settingsUnionsSingleTitle' => 'Beekeeping union',
    'settingsShippingTitle' => 'Shipment methods',
    'defaultLabel' => 'Default',
    'shipmentNameLabel' => 'Shipment name',
    'shipmentPriceLabel' => 'Cost',
    'shipmentIsFreeLabel' => 'Free shipment',
    'shipmentDateLabel' => 'Shipment date',
    'shipmentDateShortLabel' => 'Date',
    'deleteShipmentTooltip' => 'Delete shipment method',
    'shipmentAddedSuccessMessage' => 'Shipment method added successfully',
    'shipmentsDeleteSuccessMessage' => 'Shipment method deleted successfully',
    'shipmentUpdateSuccessMessage' => 'Shipment method updated successfully',
    'addNewShipmentMethodBtnLabel' => 'Add new method',
    'saveOrderSuccessMessage' => 'Orders was saved successfully',
    'cancelOrderSuccessMessage' => 'Order was cancelled',
    'addNewClubBtnLabel' => 'Add new union',
    'addNewUnionBtnLabel' => 'Add new union',
    'editUnionBtnLabel' => 'Edit union data',
    'clubEmailLabel' => 'Club email address',
    'unionEmailLabel' => 'Union email address',
    'clubNameLabel' => 'Club name',
    'unionNameLabel' => 'Union name',
    'deleteClubTooltip' => 'Delete beekeeping club',
    'deleteUnionTooltip' => 'Delete beekeeping union',
    'clubAddedSuccessMessage' => 'Club added successfully',
    'unionAddedSuccessMessage' => 'Union added successfully',
    'clubsDeleteSuccessMessage' => 'Club deleted successfully',
    'unionsDeleteSuccessMessage' => 'Union deleted successfully',
    'clubUpdateSuccessMessage' => 'lub updated successfully',
    'unionUpdateSuccessMessage' => 'Union updated successfully',
    'clubsCardSubtitle' => 'Beekeeping clubs are used in case when client order is processed within beekeeping club. Each club can be assign to an union.',
    'unionsCardSubtitle' => 'Beekeeping unions are used in case when client order is processed within beekeeping union.',
    'unions404Subtitle' => 'The list is empty, you can add first entry by clicking on a button in the bottom right corner.',
    'shipmentCardSubtitle' => 'You can specify multiple shipment methods for your order. For example you can add classic postal shipment or pickup in location.',
    'productNameLabel' => 'Product name',
    'productCodeLabel' => 'Product code',
    'productRegularPriceLabel' => 'Regular price',
    'productBulkPriceLabel' => 'Bulk price',
    'productPriceShortLabel' => 'Price',
    'productSumShortLabel' => 'Sum',
    'productTypeLabel' => 'Category',
    'productTypeQueen' => 'Queen',
    'productTypeOther' => 'Other',
    'settingsProductsTitle' => 'Your products',
    'productsCardSubtitle' => 'You can specify multiple products that will be available in your apiary.',
    'deleteProductTooltip' => 'Delete product',
    'addNewProductBtnLabel' => 'Add new product',
    'defineNewProductBtnLabel' => 'Define new product',
    'productAddedSuccessMessage' => 'Product added successfully',
    'productsDeleteSuccessMessage' => 'Product deleted successfully',
    'productUpdateSuccessMessage' => 'Product updated successfully',
    'clientDisplayNameLabel' => 'Client name',
    'clientFirstNameLabel' => 'First name',
    'clientLastNameLabel' => 'Last name',
    'clientPhoneLabel' => 'Phone',
    'clientPhoneShortLabel' => 'P',
    'clientEmailLabel' => 'Email',
    'clientAddressLabel' => 'Address',
    'clientsDeleteSuccessMessage' => 'Client was deleted successfully',
    'clientsCreatedSuccessMessage' => 'Client was added successfully',
    'clientsUpdatedSuccessMessage' => 'Client was edited successfully',
    'fabAddClientTooltip' => 'Add new client',
    'fabClientEditTitle' => 'Edit client',
    'fabClientChangeTitle' => 'Add and replace client',
    'clientBasicDataTitle' => 'Basic data',
    'clientAddressDataTitle' => 'Shipping address data',
    'inputAddressStreetLabel' => 'Street',
    'inputAddressBuildingNumberLabel' => 'Building number',
    'inputAddressApartmentNumberLabel' => 'Apartment number',
    'inputAddressPostCodeLabel' => 'Postal code',
    'inputAddressCityLabel' => 'City',
    'searchByLabel' => 'Search clients',
    'searchOrdersByLabel' => 'Search orders',
    'searchShipmentsByLabel' => 'Search shipments',
    'searchOrdersHintLabel' => 'You can search by order number, client name, phone, email address or by beekeeping union name',
    'clientOrderClubLabel' => 'Client beekeeping union',
    'clientOrderClubLabelShort' => 'Beekeeping club',
    'clientOrderClubLabelSuperShort' => 'Club',
    'clientOrderUnionLabelShort' => 'Beekeeping union',
    'clientOrderUnionLabelSuperShort' => 'Union',
    'clientCommentLabel' => 'Comment',
    'clientWarningLabel' => 'Cooperation status',
    'clientAdditionalDataTitle' => 'Additional data',
    'clientCommentsTitle' => 'Client cooperation information',
    'clientCooperationNullLabel' => 'All good',
    'clientCooperationWarningLabel' => 'Warning',
    'clientCooperationBlockListLabel' => 'Block list',
    'notes' => 'Notes',

    // Orders
    'fabAddOrderTooltip' => 'Add new order',
    'detailsPageTitle' => 'Order',
    '404Subtitle' => 'Order you are trying to reach does not exist in our system.',
    'detailsPageBackBtnLabel' => 'Orders list',
    'lastUpdatedLabel' => 'Last updated',
    'createdLabel' => 'Created',
    'createdAtLabel' => 'Created at',
    'client' => [
        'cardTitle' => 'Main client',
    ],
    'productsDataTitle' => 'Products',
    'shipmentsDataTitle' => 'Shipment',
    'shipmentsDayTitle' => 'Shipment day',
    'refundDetailsDataTitle' => 'Refund',
    'shipmentDetailsDataTitle' => 'Shipment details',
    'orderDataTitle' => 'Order details',
    'orderTypeLabel' => 'Refunded order',
    'orderTypeShortLabel' => 'Refunded',
    'source' => [
        'label' => 'Order source',
        'phone' => 'Phone',
        'mail' => 'E-mail',
        'direct' => 'Direct',
        'other' => 'Other',
    ],
    'orderCommentLabel' => 'Comment to the order',
    'orderIsBulkLabel' => 'Bulk order',
    'orderIsConfirmedByClientLabel' => 'Confirmed by client',
    'orderIsConfirmedByClientShortLabel' => 'Confirmation',
    'orderIsNotConfirmedByClientLabel' => 'Not confirmed by client',
    'orderIsRefundConfirmedLabel' => 'Refund confirmed',
    'orderIsRefundNonConfirmedLabel' => 'Refund not confirmed',
    'ordersDeleteSuccessMessage' => 'Order was deleted successfully',
    'shipmentConfirmedSuccessfully' => 'Shipment was confirmed successfully',
    'updateSuccessMessage' => 'Order was updated successfully',
    'priceSummaryLabel' => 'Sum',
    'confirmBtnLabel' => 'Confirm',
    'shipmentDateChangedSuccessfully' => 'Shipment date was changed successfully',
    'disableRefundLabel' => 'Disable refundation',
    'enableRefundLabel' => 'Enable refundation',
    'duplicateOrderLabel' => 'Duplicate',

    //order status
    'statusHeadline' => 'Order status',
    'refundHeadline' => 'Refunded',
    'status_null' => '--',
    'status_draft' => 'Draft',
    'status_new' => 'New',
    'status_confirmed' => 'Confirmed',
    'status_unconfirmed' => 'Unconfirmed',
    'status_completed' => 'Completed',
    'status_sent' => 'Sent',
    'status_cancelled' => 'Cancelled',
    'status_prepared' => 'Packed',
    'status_ready' => 'Ready',
    'status_active' => 'Active',
    'status_paid' => 'Paid',
    'status_all' => 'All',
    'cancelBtnLabel' => 'Cancel this order',

    //Client details
    'clientLabel' => 'Client',
    'clientPayingLabel' => 'Payer',
    'queenReceiverLabel' => 'Direct Order Receiver',
    'invoiceLabel' => 'Invoicing',
    'clientSearchPlaceholder' => 'Start typing to search for clients',
    'clubSearchPlaceholder' => 'Start typing to search for union',
    'noDataForClientSearch' => 'No results',

    //Product detals
    'productLabel' => 'Product',
    'productSearchPlaceholder' => 'Start writing to search for a product',
    'productCountLabel' => 'Count',
    'showAdvancedBtnLabel' => 'Advanced',
    'productRefundedLabel' => 'Refunded',
    'advancedSettingsTitle' => 'Advanced settings',
    'otherDataTitle' => 'Other',
    'unionSearchPlaceholder' => 'Start writing to search for an union',
    'noDateSetLabel' => 'No date set yet',

    //Queen Types
    'productQueenTypeLabel' => 'Queen type in system',
    'productQueenTypeShortLabel' => 'Queen type',
    'productQueenType_null' => '--',
    'productQueenType_nu' => 'Virgin queen',
    'productQueenType_un' => 'Inseminated naturally',
    'productQueenType_us' => 'Inseminated artificially',
    'productQueenType_uss' => 'Inseminated artificially with confirmed brood',
    'productQueenType_nucs' => 'Nucleus',

    //Shipments
    'addNewShipmentBtnLabel' => 'Add new shipment',
    'deleteShipmentSuccessMessage' => 'Shipment removed successfully',
    'addShipmentSuccessMessage' => 'Shipment added successfully',
    'showClientInformation' => 'Change client',
    'shipmentClientLabel' => 'Recipient',
    'shipmentClientShortLabel' => 'Recipient',
    'shipmentSentLabel' => 'Sent',
    'shipmentWaitingLabel' => 'Awaiting',
    'shipmentSentLongLabel' => 'Shipment sent',
    'shipmentPreparedLabel' => 'Prepared',
    'shipmentPreparedLongLabel' => 'Shipment prepared',
    'shipmentBasketLabel' => 'Products',
    'shipmentValueLabel' => 'Value',
    'shipmentSeeDetailsBtnLabel' => 'See order details',
    'shipmentMethodLabel' => 'Method',
    'shipmentNoDateTitle' => 'Shipment date not selected',
    'shipmentTypeLabel' => 'Shipment type',
    'isShipmentNumberGeneratedLabel' => 'Shipment document generated',
    'shipmentNumberLabel' => 'Shipping number',

    //Client company data
    'clientCompanyDataTitle' => 'Company data',
    'inputCompanyAddressLabel' => 'Address',
    'inputCompanyTaxNumberLabel' => 'Company tax number',
    'inputCompanyNameLabel' => 'Company full name',
    'inputCompanyPostCodeLabel' => 'Postal code',
    'inputCompanyCityLabel' => 'City',
    'maskHint' => 'Write without spaces or dashes',

    //Shipment date proposition
    'shipmentDatePropTitle' => 'Choose shipment date',
    'shipmentDatePropShortTitle' => 'Choose date',
    'chooseBtnLabel' => 'Save',
    'chooseBtnTooltip' => 'Selected day',
    'selectBtnLabel' => 'Select',
    'todayBtnLabel' => 'Today',
    'nextPeriodBtnLabel' => 'Next month',
    'prevPeriodBtnLabel' => 'Previous month',
    'addProductsToSeeLabel' => 'Add products to set a shipment date',
    'collapseShipmentDayCard' => 'Collapse card',
    'expandShipmentDayCard' => 'Expand card',
    'prognosedLimitWarning' => 'There is a possibility to exceed the prognosed limit of queens for that day',
    'prognosedLabel' => 'Prognosed',
    'orderedLabel' => 'Ordered',
    'differenceLabel' => 'Difference',

    //Queen insemination statuses
    'queen_vq' => 'VQ',
    'queen_mq' => 'MQ',
    'queen_ai' => 'AI',
    'queen_aib' => 'AIB',

    //Warnings
    'warning_headline' => 'Client data incomplete',
    'warning_noClient' => 'No client selected',
    'warning_noPhone' => 'phone not added to the client',
    'warning_noAddressData' => 'address data incomplete',

    //Invoice panel
    'invoicePreparedLabel' => 'Invoice prepared for shipment',

    'table' => [
        'seasonHint' => 'from :startDate to :endDate',
        'numberLabel' => 'Number',
        'statusLabel' => 'Status',
        'clientDisplayNameLabel' => 'Client',
        'goToOrderBtnLabel' => 'Go to details',
        'progressLabel' => 'Completeness',
        'seasonNullLabel' => 'Season: --',
        '404Subtitle' => 'We didn\'t find any orders for your account. If you want to begin, please add first order using button in right bottom corner.',
        '404OrderTableSubtitle' => 'There are no shipments found for this order. Please add first shipment to begin.',
        'queenLineLabel' => 'Line',
        'shipment' => [
            'settingsLabel' => 'Shipment details',
            'documentsLabel' => 'Shipment documents',
        ],
        '404NoShipmentForThisDay' => 'There are no shipments planned for today.',
        'but' => 'but',
        'goToOrders' => 'Go to orders',
        'noProductsInOrder' => 'There are no products added to this order',
    ],
    'child' => [
        'otherLabel' => 'Other',
    ],
    'queenTypes' => [
        'nu' => 'VQ',
        'un' => 'MQ',
        'us' => 'AI',
        'uss' => 'AIC',
        'nucs' => 'Nucs',
    ],
    'files' => [
        'emptyTitle' => 'Attached files',
        'title' => 'Attached files (:value)',
        'addFile' => 'Add new file',
    ],
];
