<?php
return [
    'pageTitle' => 'Queen Series',
    'pageSubtitle' => 'You can plan and manage the queen series in your apiary. Queen Series will help you with planning activities before actual queens are born.',
    'addSuccessMessage' => 'New serie was added successfully.',
    'deleteSuccessMessage' => 'Serie :name was deleted successfully.',
    'updateSuccessMessage' => 'Serie :name was updated successfully.',
    'transferredAtLabel' => 'Transfer of larvae date',
    'joinedAtLabel' => 'Joining date',
    'isolatedAtLabel' => 'Isolation date',
    'bornAtLabel' => 'Born date',
    'serieMaxCountLabel' => 'Expected count of queens',
    'fabAddNewSerieTooltip' => 'Add new serie',
    'newSerieInfoTitle' => 'What are series for in our application?',
    'newSerieInfoDesc' => 'With series, you can plan better from the moment of moving larvae to the time when queens are born in the incubator. Created series are compared with sales prognosis based on your orders, giving you input about how many orders can you handle over the season.',
    'serieNameLabel' => 'Serie name',
    'manualEfficiencyLabel' => 'Use default efficiency set',
    'editSerieModalTitle' => 'Edit serie',
    'startDateLabel' => 'Start date',
    'endDateLabel' => 'End date',
    'addMultipleSerieSuccessMessage' => 'Series were added successfully',
    'addMultipleSeriesModalHivesPrefixLabel' => 'Prefix of serie name',
    'addMultipleSeriesModalTitle' => 'Add multiple series',
    'addMultipleSeriesModalInfoBoxTitle' => 'Created series overview',
    'noHivesInfoBox' => 'Fill the start and end date to see examples of created series.',
    'saveOnlyThisSerieLabel' => 'Change only this one',
    'saveAllSeriesThisLabel' => 'Change this and next series',
    'revealSerieTitle' => 'List of series',
    'revealSerieSubtitle' => 'This series was created in a set with other series. Do you want to change the dates as well for the next series from the list?',
    'defaultEfficiencyInfo' => 'By default, the series uses a dynamic calculation of the effectiveness of each step. If you want to force the use of default values, check this option.',

    //Statistics
    'lostBornCountLabel' => 'Count of: lost during born',
    'joinedCountLabel' => 'Count of: joined',
    'isolatedCountLabel' => 'Count of: isolated',
    'transferredCountLabel' => 'Count of: transferred larvae',
    'realCountLabel' => 'Real count of born queens',
    'prognosedCountLabel' => 'Prognosed count of born queens',
    'efficiencyLabel' => 'Efficiency',
    'efficiencyJoinedLabel' => 'Efficiency',

    'workCardTitle' => 'Queen series',
    'workCardInfoTitle' => 'What is this panel used for?',
    'workCardSubTitle' => 'If you are using queen series in our application - in this panel you will find the series which require your action today. Data provided here is used for queen availability prognosis.',
    'day_transferred' => 'Transfer day',
    'day_joined' => 'Joining day',
    'day_isolated' => 'Isolation day',
    'day_born' => 'Born day',
    'allGoodText' => 'All good here! There is nothing to work on here today or all tasks were already completed',

];
