<?php
return [
    'nav' => [
        'apiaryLabel' => 'Apiary',
        'apiaryLogo' => 'Logo',
        'teamLabel' => 'Team',
        'queenLinesLabel' => 'Queen lines',
        'seasonsLabel' => 'Seasons',
    ],
    'general' => [
        'pageTitle' => 'Settings',
        'subTitle' => 'You can manage your apiary settings here.',
    ],
    'apiary' => [
        'cardTitle' => 'Apiary details',
    ],
    'efficiency' => [
        'cardTitle' => 'Efficiency settings',
    ],
    'queenLines' => [
        'cardTitle' => 'Queen Lines',
        'subTitle' => 'You can manage your queen lines here.
                            <br/>If you are no longer need a queen line, you can either delete it or disable it in the application.',
    ],
    'seasons' => [
        'cardTitle' => 'Seasons',
        'cardTitleSingular' => 'Season',
        'subTitle' => 'Seasons allow you to divide orders and activities in the apiary into defined periods. You can add new seasons in the past and future, and we will try to match parts of the application to the seasons set.',
        'nameLabel' => 'Name',
        'startDateLabel' => 'Start date',
        'endDateLabel' => 'End date',
        '404Subtitle' => 'There are no defined seasons yet, please add first to start.',
        'addSuccessMessage' => 'Season was added successfully.',
        'updateSuccessMessage' => 'Season was updated successfully.',
        'deleteSuccessMessage' => 'Season :name was deleted successfully.',
        'editModalTitle' => 'Edit season :name',
        'addModalTitle' => 'Add new season',
    ],
    'queenLinesNameSingular' => 'Queen line',
    'queenLinesNameLabel' => 'Short name',
    'queenLinesFullNameLabel' => 'Full name',
    'queenLinesNameLabelShort' => 'Line',
    'allQueenLinesLabel' => 'All lines',
    'beeSubspeciesNameLabel' => 'Subspecies',
    'queenLineActiveNameLabel' => 'Active',
    'clubActiveNameLabel' => 'Active',
    'unionActiveNameLabel' => 'Active',
    'queenLineNotActiveNameLabel' => 'Inactive',
    'clubNotActiveNameLabel' => 'Inactive',
    'a_m_mellifera' => 'A. m. mellifera',
    'a_m_carnica' => 'A. m. carnica',
    'a_m_caucasica' => 'A. m. caucasica',
    'a_m_ligustica' => 'A. m. ligustica',
    'queen_lines' => [
        'a_m_mellifera' => 'A. m. mellifera',
        'a_m_carnica' => 'A. m. carnica',
        'a_m_caucasica' => 'A. m. caucasica',
        'a_m_ligustica' => 'A. m. ligustica',
    ],
    'crossbreed' => 'Cross-breed',
    'hybrid' => 'Hybrid',
    'deleteQueenLineSuccessMessage' => 'Queen line :name was deleted successfully',
    'queenLineUpdateSuccessMessage' => 'Queen line :name was updated successfully',
    'queenLineAddedSuccessMessage' => 'Queen line :name was added successfully',
    'addNewQueenLineBtnLabel' => 'Add new queen line',
    'deleteQueenLineTooltip' => 'Delete this queen line',
    'deleteQueenLineInfoTooltip' => 'This line is alone or has at least one existing queen in our system. Therefore we cannot delete it. Instead, you can deactivate it, and it won\'t be visible in our application.',
    'apiarySettingsPageTitle' => 'Apiary settings',
    'apiarySettingsSubtitle' => 'You can manage your apiary settings here.',
    'apiaryCardTitle' => 'Main settings',
    'globalEfficiencyLabel' => 'Global efficiency',
    'globalEfficiencyHint' => 'Global efficiency is used when locations efficiency cannot be yet calculated.',
    'seriesEfficiencyLabel' => 'Series efficiency',
    'seriesIsolationEfficiencyLabel' => 'Series isolation efficiency',
    'seriesBornEfficiencyLabel' => 'Series born efficiency',
    'seriesEfficiencyHint' => 'Series efficiency is used for prognosis calculation - as initial value.',
    'updatedSuccess' => 'Settings were updated successfully',

    'invoice' => [
        'cardTitle' => 'Invoicing details',
        'inputAddressStreetLabel' => 'Street',
        'inputAddressBuildingNumberLabel' => 'Building number',
        'inputAddressApartmentNumberLabel' => 'Apartment number',
        'inputAddressPostCodeLabel' => 'Postal code',
        'inputAddressCityLabel' => 'City',
        'companyNameLabel' => 'Company name',
        'inputVatNumberLabel' => 'VAT number',
        'inputVatNumberShortLabel' => 'VAT',
        'noInvoiceDataWarning' => 'Invoicing data incomplete',
        'nrbLabel' => 'Bank account',
    ],
    'contact' => [
        'cardTitle' => 'Contact details',
        'inputContactEmailLabel' => 'Email',
        'inputContactPhoneLabel' => 'Phone number',
    ],
    'apiaryLogo' => [
        'cardTitle' => 'Apiary logo',
        'cardSubTitle' => 'You can upload your customized apiary logotype. We can use it in generated pdf files and in application layout.',
        'uploadForm' => [
            'cardTitle' => 'Upload new logo',
            'cardSubTitle' => 'File restrictions: size max 500kB, format: png, jpg, jpeg.',
            'inputFile' => 'Choose file',
        ],
    ]
];
