<?php
return [
    'accountAppName' => 'Account',
    'apiaryAppName' => 'My Apiary',
    'clubAppName' => 'Club',
    'queensAppName' => 'Queen Breeders',
    'logoutBtnLabel' => 'Log out',
    'createdBy' => 'Created by',
    'createdAt' => 'Created at',
    'workInProgessHeadline' => 'Work in progress.',
    'workInProgessSubheadline' => 'Our hardworking bees are working on making improvements here. Please come back soon!',
    'placeholderTitle' => 'Example page title',
    'cancelBtnLabel' => 'Cancel',
    'closeBtnLabel' => 'Close',
    'saveBtnLabel' => 'Save',
    'addBtnLabel' => 'Add',
    'deleteBtnLabel' => 'Delete',
    'printBtnLabel' => 'Print',
    'filterBtnLabel' => 'Filter',
    'confirm' => 'Please confirm:',
    'search' => 'Search',
    'goBack' => 'Go back',
    'new' => 'New',
    'owner' => 'Owner',
    'noResults' => 'No results to show',
    'noResultsForSelectedDay' => 'There are no results for selected day.',
    'partnerPszczelarzaURI' => 'https://partnerpszczelarza.pl',
    'today' => 'today',
    'loadingDataMsg' => 'Loading data for you...',
    'continueBtnLabel' => 'Next step',
    'savencontinueBtnLabel' => 'Save and continue',
    'detailsBtnLabel' => 'Details',
    'editBtnLabel' => 'Edit',
    'moveBtnLabel' => 'Move',
    'showBtnLabel' => 'See details',
    'errorOccurredMessage' => 'An error occurred during this action, please try again.',
    'getBackToHomepageBtnLabel' => 'Get back to Home page',
    '401AltTitle' => 'Unauthorized!',
    '401Title' => 'Oops!',
    '401Subtitle' => 'It seems that you don\'t have rights to see this page. <br/>Please contact the apiary owner to find a solution.',
    'onLabel' => 'On',
    'offLabel' => 'Off',
    'archiveBtnLabel' => 'Archive',
    '404Title' => 'It\'s empty here!',
    '404Subtitle' => 'We do not have anything to show here yet.',
    'undefinedLabel' => 'Not found',
    'scrollToTopLabel' => 'Back to top',
    'dataTable' => [
        'allOptionLabel' => 'All',
        'rowsPerPageLabel' => 'Rows per page',
        'pageText' => '{0}-{1} of {2}',
    ],
    'accept' => 'Accept',
    'reject' => 'Reject',
    'true' => 'Yes',
    'false' => 'No',
    'copy' => '-copy',
    'uploadBtn' => 'Upload',
    'chooseBtn' => 'Choose',
    'downloadBtn' => 'Download',
    'optionalFields' => 'Optional fields',
    'goToSubscriptionPageBtn' => 'Upgrade your account',
    'actionsLabel' => 'Actions',
    'orText' => 'or',
    'links' => [
        'documentation' => [
            'text' => 'Documentation',
            'href' => 'https://partnerpszczelarza.pl/aplikacja-hodowcy/dokumentacja/',
        ],
        'privacyPolicy' => [
            'text' => 'Privacy Policy',
            'href' => 'https://partnerpszczelarza.pl/polityka-prywatnosci',
        ],
    ],
    'refreshBtn' => 'Refresh',

    // time
    'today' => 'today',
    'thisWeek' => 'this week',
    'thisMonth' => 'this month',
    'thisYear' => 'this year',
    'customDateRange' => 'custom dates',
    'from' => 'from',
    'to' => 'to',
    'dataTable' => [
        'allOptionLabel' => 'All',
        'rowsPerPageLabel' => 'Rows per page',
        'pageText' => '{0}-{1} of {2}',
    ],
];
