<?php

return [
    'pageTitle' => 'Dronning batcher',
    'pageSubtitle' => 'Queen batcher brukes på lokasjonssiden for raskt å legge til dronninger i bikubene deres. På denne siden kan du administrere sett, dele dem på bestemte steder og følge statistikken for hver batch.',
    'lineLabel' => 'Dronning linje',
    'confirmedLabel' => 'bekreftet',
    'potentiallyBroodingLabel' => 'potensielt avl',
    'virginQueensLabel' => 'jomfru dronninger',
    'nameLabel' => 'Batch navn',
    'daysOfLifeLabel' => 'Dager i livet',
    'cycleLengthLabel' => 'Sykluslengde',
    'serieLabel' => 'Serie',
    'weeksLabel' => 'uker',
    'soldLabel' => 'solht',
    'lostLabel' => 'mistet',
    'efficiencyLabel' => 'effektivitet',
    'fabAddNewTooltip' => 'Legg til ny batch',
    'editBatchLabel' => 'Rediger batch',
    'efficiencyTooltip' => 'Batcheffektiviteten vil være synlig hvis antall dronninger solgt, tapt og bekreftet vil overstige 25 % av batchstørrelsen.',
    'infoTitle' => 'Hva brukes dronningbatcher til?',
    'infoDescription' => 'Dronning batcher er en del av serien og du kan enkelt legge til dronninger i bikubene med ett klikk. Du kan sette opp en batch for hver dronnings linje og plassering. Senere vil du se statistikk for hver batch.',
    'addSuccessMessage' => 'Ny batch ble lagt til.',
    'deleteSuccessMessage' => 'Batchen ble slettet.',
    'updateSuccessMessage' => 'Batch :name ble oppdatert.',
    'locationShortLabel' => 'plassering',
    'disposedShortLabel' => 'Avhendet',
    'limitShortLabel' => 'Grense',
    'emptyHives' => 'tomme bikuber',
];
