<?php
return [
    'fabAddNewLocationTooltip' => 'Legg til ny plassering',
    'fabAddNewHiveTooltip' => 'Legg til ny bikube',
    'fabAddMultipleHivesTooltip' => 'Legg til flere bikuber',
    'fabAddNewSectionTooltip' => 'Legg til ny seksjon',
    'summaryPageTitle' => 'Stedssammendrag',
    'pageSubtitle' => 'Her kan du se din nåværende status for alle plasseringer i bigården din.',
    'addLocationSuccessMessage' => 'Ny plassering ble lagt til.',
    'deleteLocationSuccessMessage' => 'Plasseringen ble slettet.',
    'updateLocationSuccessMessage' => 'Plasseringen ble oppdatert.',
    'hives' => '{0} kuber|{1} kube|[2,*] kuber',
    'locationLabel' => 'Plassering',
    'sectionLabel' => 'Seksjon',
    'generalSectionName' => 'Hoveddel',
    'moveSectionUpTooltip' => 'Flytte opp',
    'moveSectionDownTooltip' => 'Flytte ned',
    'countInStatisticsTooltip' => 'Dronninger fra denne seksjonen regnes med i salgsprognosen.',
    'notCountInStatisticsTooltip' => 'Dronninger fra denne seksjonen regnes ikke med i salgsprognosen.',
    'addNewSectionCardTitle' => 'Legg til ny seksjon',
    'editSectionCardTitle' => 'Rediger seksjon',
    'addNewLocationNameLabel' => 'Skriv inn stedsnavn',
    'newSectionNameLabel' => 'Skriv inn seksjonsnavn',
    'selectLocationLabel' => 'Velg plassering',
    'sectionSwitchSalesStatsLabel' => 'Aktiver telling av dronninger fra denne delen i salgsprognose',
    'addSectionSuccessMessage' => 'Seksjon opprettet!',
    'deleteSectionSuccessMessage' => 'Delen ble slettet.',
    'updateSectionSuccessMessage' => 'Delen ble oppdatert.',
    'sectionsInfoTitle' => 'Hva er seksjoner for?',
    'sectionsInfoDesc' => '<p class="mb-1 pl-3">Seksjoner kan hjelpe deg med å dele plasseringen i mindre deler, og dermed gi en bedre refleksjon av bigårdens plan.</p>
                                    <p class="mb-1 pl-3">
                                        Du kan også skille dronninger som ikke er inkludert i "dronninger tilgjengelig for salg"-prognoser med seksjoner.
                                    </p>
                                    <p class="mb-1 pl-3">For eksempel, hvis noen få dronninger på et gitt sted ikke er til salgs, kan du legge dem i en egen seksjon.</p>',
    'selectLocationSectionLabel' => 'Velg en seksjon',
    'addNewHiveNameLabel' => 'Skriv inn bikubenavn',
    'newHiveModalTitle' => 'Legg til ny bikube',
    'editHiveModalTitle' => 'Rediger bikube',
    'newHiveInfoTitle' => 'Hvordan brukes bikubene i vår applikasjon?',
    'newHiveInfoDesc' => '<p class="mb-1 pl-3">Bikuber i applikasjonen vår er designet for å avle én enkelt dronning om gangen.
                            </p><p class="mb-1 pl-3">Så hvis du bruker bikuber med flere kammer, legg til hvert kammer som en separat bikube.</p>',
    'addSingleHiveSuccessMessage' => 'Hive opprettet vellykket! Du kan legge til en til eller lukke denne boksen.',
    'addMultipleHiveSuccessMessage' => 'Bikuber ble lagt til!',
    'editSingleHiveSuccessMessage' => 'Bikuben ble redigert.',
    'deleteSingleHiveSuccessMessage' => 'Bikube :hiveName slettet.',
    'moveToWarehouseLabel' => 'Flytte til lageret',
    'moveHiveToWarehouseSuccessMessage' => 'Bikube :hiveName ble flyttet til lageret',
    'saveAndMoveBtnLabel' => 'Lagre og flytt',
    'addMultipleHivesModalTitle' => 'Legg til flere bikuber',
    'addMultipleHivesModalInfoBoxTitle' => 'Navn på opprettede bikuber:',
    'addMultipleHivesModalHivesNumberLabel' => 'Hvor mange bikuber vil du legge til?',
    'addMultipleHivesModalHivesNumberStartLabel' => 'Med hvilket nummer skal de begynne?',
    'addMultipleHivesModalHivesSuffixLabel' => 'Skal det legges til et "a/b"-suffiks?',
    'addMultipleHivesModalHivesPrefixLabel' => 'Hvordan vil du sette prefiks til bikubene?',
    'inWarehouseLabel' => 'På lageret',
    'addMultipleHivesModalLocationLabel' => 'Plasser nye bikuber på plassering',
    'hivesNumberValidationLabel' => 'antall bikuber?',
    'hivesNumberStartValidationLabel' => 'nummer',
    'hivesNumberHint' => 'Du kan legge til opptil 200 bikuber i én handling',
    'noHivesInfoBox' => 'Fyll ut feltene på venstre side for å se flere detaljer.',
    'filterByNameLabel' => 'Søk etter et bikubenavn',
    'showEmptyLabel' => 'Vis kun tomme bikuber',
    'enableFiltersBtnLabel' => 'Filter bikuber',

    //Queens
    'addNewQueenBtnLabel' => 'Legg til ny dronning',
    'queenAddedSuccessMessage' => 'Dronning lagt til',
    'queenEditedSuccessMessage' => 'Dronningen ble redigert',
    'queenDeletedSuccessMessage' => 'Dronning ble slettet',
    'editQueenModalTitle' => 'Rediger dronning i bikuben',
    'editQueenModalTitleShort' => 'Rediger dronning',
    'addQueenModalTitle' => 'Legg dronning til bikuben',
    'queenDOBLabel' => 'Fødselsdato',
    'queenDayOfLifeLabel' => 'Alder (days)',
    'queenCycleLengthLabel' => 'Sykluslengde',
    'weeksLabel' => 'uker',
    'deleteWarningLabel' => 'Sletting av dronningen vil føre til irreversibelt tap i
                             systemet, det vil ikke inngå i statistikken. Hvis du vil markere det som tapt, vennligst bruk andre dronninghandlinger fra kube-menyen.',
    'queenAction_leave_PB' => 'Forlat potensielt avl',
    'queenAction_leave_MQ' => 'Forlat avlsdronning',
    'queenAction_take_PB' => 'Ta potensielt avlsdronning',
    'queenAction_take_MQ' => 'Ta parret dronning',
    'queenAction_lost' => 'Dronning tapt',

    'filters_label' => 'Avlsstatus',
    'filters_state_mq' => 'Parret dronning',
    'filters_state_pb' => 'Potensielt avl',
    'filters_state_vq' => 'Jomfru dronning',
    'filters_otherLabel' => 'annen',

    //Queen Batches
    'addQueenFromBatchLabel' => 'Legg til dronning fra batch',
    'queenBatchLabelShort' => 'Batch',
    'queenLineLabelShort' => 'Linje',
    'queenCycleLabelShort' => 'Syklus',
];
