<?php
return [
    'mainPageTitle' => 'Bestillinger',
    'mainPageSubtitle' => 'Du kan administrere bestillingene dine her. Fjernede eller lukkede bestillinger vises på den separate listen.',
    'clientsPageTitle' => 'Dine kunder',
    'clientsPageSubtitle' => 'Du kan administrere kundedataene dine her. Alle kunder vil være tilgjengelige i bestillingsseksjonen basert på denne listen.',
    'shipmentPageTitle' => 'Forsendelser',
    'shipmentPageSubtitle' => 'Du kan administrere forsendelsene dine her.',
    'settingsPageTitle' => 'Butikkinnstillingene dine',
    'settingsPageSubtitle' => 'Du kan endre innstilalingene til butikkmodulen her. Du kan administrere produktene dine, listen over birøkterforeninger og forsendelsesmetoder.',
    'statsPageTitle' => 'Ordrestatistikk',
    'statsPageSubtitle' => 'Du kan sjekke ordrestatistikken din her',
    'settingsProductTitle' => 'Dine produkter',
    'settingsClubsTitle' => 'Lokallag',
    'settingsUnionsTitle' => 'Fylkeslag',
    'settingsUnionsSingleTitle' => 'Birøktelag sentralt',
    'settingsShippingTitle' => 'Forsendelses metoder',
    'defaultLabel' => 'Standard',
    'shipmentNameLabel' => 'Type forsendelse',
    'shipmentPriceLabel' => 'Kostnad',
    'shipmentIsFreeLabel' => 'Gratis frakt',
    'shipmentDateLabel' => 'Forsendelsesdato',
    'shipmentDateShortLabel' => 'Dato',
    'deleteShipmentTooltip' => 'Slett forsendelsesmetode',
    'shipmentAddedSuccessMessage' => 'Forsendelsesmetode ble lagt til',
    'shipmentsDeleteSuccessMessage' => 'Forsendelsesmetoden ble slettet',
    'shipmentUpdateSuccessMessage' => 'Forsendelsesmetoden er oppdatert',
    'addNewShipmentMethodBtnLabel' => 'Legg til ny frakt metode',
    'saveOrderSuccessMessage' => 'Bestillinger ble lagret',
    'cancelOrderSuccessMessage' => 'Bestillingen ble kansellert',
    'addNewClubBtnLabel' => 'Legg til nytt fylkeslag',
    'addNewUnionBtnLabel' => 'Legg til fylkeslag',
    'editUnionBtnLabel' => 'Rediger fylkeslag informasjon',
    'clubEmailLabel' => 'Klubbens E-post adresse',
    'unionEmailLabel' => 'Unionens E-post adresse',
    'clubNameLabel' => 'Klubbens navn',
    'unionNameLabel' => 'Unionens navn',
    'deleteClubTooltip' => 'Slett lokallag ',
    'deleteUnionTooltip' => 'Slett fylkeslag',
    'clubAddedSuccessMessage' => 'Klubben ble lagt til',
    'unionAddedSuccessMessage' => 'Fylkeslag ble lagt til',
    'clubsDeleteSuccessMessage' => 'Klubben ble slettet',
    'unionsDeleteSuccessMessage' => 'Fylkeslag slettet',
    'clubUpdateSuccessMessage' => 'klubben ble oppdatert',
    'unionUpdateSuccessMessage' => 'Fylkeslag ble oppdatert',
    'clubsCardSubtitle' => 'Birøkterklubber brukes i tilfelle kundeordre behandles i birøkterklubben. Hver klubb kan tildeles Norges birøktelag.',
    'unionsCardSubtitle' => 'Birøkterforeninger benyttes i tilfelle kundeordre behandles innenfor birøkterlag.',
    'unions404Subtitle' => 'Listen er tom, du kan legge til første oppføring ved å klikke på en knapp nederst i høyre hjørne.',
    'shipmentCardSubtitle' => 'Du kan spesifisere flere forsendelsesmetoder for bestillingen din. Du kan for eksempel legge til klassisk postforsendelse eller henting på stedet.',
    'productNameLabel' => 'Produkt navn',
    'productCodeLabel' => 'Vare nummer',
    'productRegularPriceLabel' => 'Normal pris',
    'productBulkPriceLabel' => 'Bulk priser',
    'productPriceShortLabel' => 'Pris',
    'productSumShortLabel' => 'Sum',
    'productTypeLabel' => 'Kategori',
    'productTypeQueen' => 'Dronning',
    'productTypeOther' => 'Andre',
    'settingsProductsTitle' => 'Dine produkter',
    'productsCardSubtitle' => 'Du kan spesifisere flere produkter som vil være tilgjengelige i bigården din.',
    'deleteProductTooltip' => 'Slett produktet',
    'addNewProductBtnLabel' => 'Legg til ett nytt produkt',
    'defineNewProductBtnLabel' => 'Definer ditt produkt',
    'productAddedSuccessMessage' => 'Produktet ble lagt til',
    'productsDeleteSuccessMessage' => 'Produktet ble slettet',
    'productUpdateSuccessMessage' => 'Produktet ble oppdatert',
    'clientDisplayNameLabel' => 'Kunde navn',
    'clientFirstNameLabel' => 'Fornavn',
    'clientLastNameLabel' => 'Etternavn',
    'clientPhoneLabel' => 'Telefon',
    'clientPhoneShortLabel' => 'Tlf',
    'clientEmailLabel' => 'E-post',
    'clientAddressLabel' => 'Adresse',
    'clientsDeleteSuccessMessage' => 'Kunde ble slettet',
    'clientsCreatedSuccessMessage' => 'Kunde ble lagt til',
    'clientsUpdatedSuccessMessage' => 'Kunde ble redigert',
    'fabAddClientTooltip' => 'Legg til ny kunde',
    'fabClientEditTitle' => 'Rediger kunde',
    'fabClientChangeTitle' => 'Legg til og erstatt kunde',
    'clientBasicDataTitle' => 'Grunnleggende data',
    'clientAddressDataTitle' => 'Leverings adresse',
    'inputAddressStreetLabel' => 'Gate',
    'inputAddressBuildingNumberLabel' => 'Husnummer',
    'inputAddressApartmentNumberLabel' => 'Leilighets nummer',
    'inputAddressPostCodeLabel' => 'Postnummer',
    'inputAddressCityLabel' => 'By',
    'searchByLabel' => 'Søk kunde',
    'searchOrdersByLabel' => 'Søk bestillinger',
    'searchShipmentsByLabel' => 'Søk forsendelse',
    'searchOrdersHintLabel' => 'Du kan søke på ordrenummer, kundenavn, telefon, e-postadresse eller på birøkterforeningens navn.',
    'clientOrderClubLabel' => 'Kunde birøkterforbund sentralt',
    'clientOrderClubLabelShort' => 'Birøkterklubb lokalt',
    'clientOrderClubLabelSuperShort' => 'Klubb',
    'clientOrderUnionLabelShort' => 'Birøkterlag sentralt',
    'clientOrderUnionLabelSuperShort' => 'Forbund',
    'clientCommentLabel' => 'Kommentar',
    'clientWarningLabel' => 'Samarbeidsstatus',
    'clientAdditionalDataTitle' => 'Ytterligere data',
    'clientCommentsTitle' => 'Kunde samarbeids informasjon',
    'clientCooperationNullLabel' => 'Helt fint',
    'clientCooperationWarningLabel' => 'Advarsel',
    'clientCooperationBlockListLabel' => 'Blokkeringsliste',
    'notes' => 'Notater',

    // Orders
    'fabAddOrderTooltip' => 'Legg til ny ordre',
    'detailsPageTitle' => 'Ordre',
    '404Subtitle' => 'Ordren du prøver å nå finnes ikke i systemet vårt.',
    'detailsPageBackBtnLabel' => 'Bestillingsliste',
    'lastUpdatedLabel' => 'Sist oppdatert',
    'createdLabel' => 'Opprettet',
    'createdAtLabel' => 'Opprettet når',
    'client' => [
        'cardTitle' => 'Hoved kunde',
    ],
    'productsDataTitle' => 'Produkter',
    'shipmentsDataTitle' => 'Forsendelse',
    'shipmentsDayTitle' => 'Forsendelsesdag',
    'refundDetailsDataTitle' => 'Refundert',
    'shipmentDetailsDataTitle' => 'Forsendelse detaljer',
    'orderDataTitle' => 'Ordre detaljer',
    'orderTypeLabel' => 'Refundert ordre',
    'orderTypeShortLabel' => 'Refundert',
    'source' => [
        'label' => 'Bestillings kilde',
        'phone' => 'Telefon',
        'mail' => 'E-post',
        'direct' => 'Muntlig',
        'other' => 'Andre',
    ],
    'orderCommentLabel' => 'Kommenter bestillingen',
    'orderIsBulkLabel' => 'Bulk ordre',
    'orderIsConfirmedByClientLabel' => 'Bekreftet av klient',
    'orderIsConfirmedByClientShortLabel' => 'Bekreftelse',
    'orderIsNotConfirmedByClientLabel' => 'Ikke bekreftet av klienten',
    'orderIsRefundConfirmedLabel' => 'Refusjon bekreftet',
    'orderIsRefundNonConfirmedLabel' => 'Refusjon ikke bekreftet',
    'ordersDeleteSuccessMessage' => 'Bestillingen ble slettet',
    'shipmentConfirmedSuccessfully' => 'Forsendelsen ble bekreftet',
    'updateSuccessMessage' => 'Bestillingen ble oppdatert',
    'priceSummaryLabel' => 'Sum',
    'confirmBtnLabel' => 'Bekrefte',
    'shipmentDateChangedSuccessfully' => 'Forsendelsesdatoen ble endret',
    'disableRefundLabel' => 'Deaktiver refusjon',
    'enableRefundLabel' => 'Aktiver refusjon',
    'duplicateOrderLabel' => 'Duplisere',

    //order status
    'statusHeadline' => 'Ordre status',
    'refundHeadline' => 'Refundert',
    'status_null' => '--',
    'status_draft' => 'Utkast',
    'status_new' => 'Ny',
    'status_confirmed' => 'bekreftet',
    'status_unconfirmed' => 'Ubekreftet',
    'status_completed' => 'Fullført',
    'status_sent' => 'Sendt',
    'status_cancelled' => 'avbrutt',
    'status_prepared' => 'Pakket',
    'status_ready' => 'Klar',
    'status_active' => 'Aktiv',
    'status_paid' => 'Betalt',
    'status_all' => 'Alle',
    'cancelBtnLabel' => 'Kanseller denne bestillingen',

    //Client details
    'clientLabel' => 'Kunde',
    'clientPayingLabel' => 'Betaler',
    'queenReceiverLabel' => 'Direkte ordremottaker',
    'invoiceLabel' => 'Fakturering',
    'clientSearchPlaceholder' => 'Begynn å skrive for å søke etter klienter',
    'clubSearchPlaceholder' => 'Begynn å skrive for å søke etter birøktelag sentralt',
    'noDataForClientSearch' => 'Ingen resultater',

    //Product detals
    'productLabel' => 'Produkt',
    'productSearchPlaceholder' => 'Begynn å skrive for å søke etter et produkt',
    'productCountLabel' => 'Antall',
    'showAdvancedBtnLabel' => 'Avansert',
    'productRefundedLabel' => 'Refundert',
    'advancedSettingsTitle' => 'Avanserte innstillinger',
    'otherDataTitle' => 'Andre',
    'unionSearchPlaceholder' => 'Begynn å skrive for å søke etter en birøktelag sentralt',
    'noDateSetLabel' => 'Ingen dato satt ennå',

    //Queen Types
    'productQueenTypeLabel' => 'Dronning type i system',
    'productQueenTypeShortLabel' => 'Dronning type',
    'productQueenType_null' => '--',
    'productQueenType_nu' => 'Jomfru dronning',
    'productQueenType_un' => 'Naturlig paring ',
    'productQueenType_us' => 'Inseminert ',
    'productQueenType_uss' => 'Inseminert med bekreftet yngel',
    'productQueenType_nucs' => 'Skaksverm',

    //Shipments
    'addNewShipmentBtnLabel' => 'Legg til ny forsendelse',
    'deleteShipmentSuccessMessage' => 'Forsendelsen ble fjernet',
    'addShipmentSuccessMessage' => 'Forsendelsen ble lagt til',
    'showClientInformation' => 'Bytt kunde',
    'shipmentClientLabel' => 'Mottaker',
    'shipmentClientShortLabel' => 'Mottaker',
    'shipmentSentLabel' => 'Sendt',
    'shipmentWaitingLabel' => 'Venter',
    'shipmentSentLongLabel' => 'Sending sendt',
    'shipmentPreparedLabel' => 'Forberedt',
    'shipmentPreparedLongLabel' => 'Forsendelse klargjort',
    'shipmentBasketLabel' => 'Produkter',
    'shipmentValueLabel' => 'Verdi',
    'shipmentSeeDetailsBtnLabel' => 'Se bestillingsdetaljer',
    'shipmentMethodLabel' => 'Metode',
    'shipmentNoDateTitle' => 'Forsendelsesdato ikke valgt',
    'shipmentTypeLabel' => 'Forsendelsestype',
    'isShipmentNumberGeneratedLabel' => 'Forsendelsesdokument generert',
    'shipmentNumberLabel' => 'Fraktnummer',

    //Client company data
    'clientCompanyDataTitle' => 'Bedrifts info',
    'inputCompanyAddressLabel' => 'Adresse',
    'inputCompanyTaxNumberLabel' => 'Bedrifts mva nummer',
    'inputCompanyNameLabel' => 'Selskapets fulle navn',
    'inputCompanyPostCodeLabel' => 'Postnummer',
    'inputCompanyCityLabel' => 'By',
    'maskHint' => 'Skriv uten mellomrom eller bindestreker',

    //Shipment date proposition
    'shipmentDatePropTitle' => 'Velg forsendelsesdato',
    'shipmentDatePropShortTitle' => 'Velg dato',
    'chooseBtnLabel' => 'Lagre',
    'chooseBtnTooltip' => 'Valgt dag',
    'selectBtnLabel' => 'Velg',
    'todayBtnLabel' => 'Idag',
    'nextPeriodBtnLabel' => 'Neste måned',
    'prevPeriodBtnLabel' => 'Forrige måned',
    'addProductsToSeeLabel' => 'Legg til produkter for å angi en forsendelsesdato',
    'collapseShipmentDayCard' => 'Skjul kortet',
    'expandShipmentDayCard' => 'Utvid kortet',
    'prognosedLimitWarning' => 'Det er en mulighet for å overskride den anslåtte grensen for dronninger for den dagen',
    'prognosedLabel' => 'Prognostisert',
    'orderedLabel' => 'Bestilt',
    'differenceLabel' => 'Forskjell',

    //Queen insemination statuses
    'queen_vq' => 'JD',
    'queen_mq' => 'PD',
    'queen_ai' => 'I',
    'queen_aib' => 'IMY',

    //Warnings
    'warning_headline' => 'Klientdata er ufullstendige',
    'warning_noClient' => 'Ingen klient er valgt',
    'warning_noPhone' => 'Telefonen er ikke lagt til kunden',
    'warning_noAddressData' => 'Adressedata er ufullstendige',

    //Invoice panel
    'invoicePreparedLabel' => 'Faktura klargjort for forsendelse',

    'table' => [
        'seasonHint' => 'fra :startDate to :endDate',
        'numberLabel' => 'Nummer',
        'statusLabel' => 'Status',
        'clientDisplayNameLabel' => 'Kunde',
        'goToOrderBtnLabel' => 'Gå til detaljer',
        'progressLabel' => 'Fullstendighet',
        'seasonNullLabel' => 'Sesong: --',
        '404Subtitle' => 'Vi fant ingen bestillinger for kontoen din. Hvis du vil begynne, legg til første bestilling ved å bruke knappen nederst til høyre.',
        '404OrderTableSubtitle' => 'Det er ingen forsendelser funnet for denne bestillingen. Legg til første forsendelse for å begynne.',
        'queenLineLabel' => 'Linje',
        'shipment' => [
            'settingsLabel' => 'Forsendelse detaljer',
            'documentsLabel' => 'Forsendelsesdokumenter',
        ],
        '404NoShipmentForThisDay' => 'Det er ingen forsendelser planlagt i dag.',
        'but' => 'men',
        'goToOrders' => 'Gå til bestillinger',
        'noProductsInOrder' => 'Det er ingen produkter lagt til denne bestillingen',
    ],
    'child' => [
        'otherLabel' => 'Andre',
    ],
    'queenTypes' => [
        'nu' => 'JD',
        'un' => 'PD',
        'us' => 'I',
        'uss' => 'IMY',
        'nucs' => 'Skaksverm',
    ],
    'files' => [
        'emptyTitle' => 'Vedlagte filer',
        'title' => 'Vedlagte filer (:value)',
        'addFile' => 'Legg til ny fil',
    ],
];
