<?php
return [
    'mainPageTitle' => 'Bestillingsliste',
    'mainPageSubtitle' => 'Du kan administrere bestillingene dine her. Fjernede eller lukkede bestillinger vises på den separate listen.',
    'clientsPageTitle' => 'Dine kunder',
    'clientsPageSubtitle' => 'Du kan administrere kundedataene dine her. Alle kunder vil være tilgjengelige i bestillingsseksjonen basert på denne listen.',
    'shipmentPageTitle' => 'Forsendelser',
    'shipmentPageSubtitle' => 'Du kan administrere forsendelsene dine her.',
    'settingsPageTitle' => 'Butikkinnstillingene dine',
    'settingsPageSubtitle' => 'Du kan endre innstillingene til butikkmodulen her. Du kan administrere produktene dine, listen over birøkterforeninger og forsendelsesmetoder.',
    'statsPageTitle' => 'Bestillingsstatistikk',
    'statsPageSubtitle' => 'Du kan sjekke ordrestatistikken din her',
    'settingsProductTitle' => 'Dine produkter',
    'settingsClubsTitle' => 'Birøkterklubber',
    'settingsUnionsTitle' => 'Birøkterlag',
    'settingsUnionsSingleTitle' => 'Birøkterforeningen',
    'settingsShippingTitle' => 'Forsendelsesmetoder',
    'defaultLabel' => 'standardverdier',
    'shipmentNameLabel' => 'Navn på forsendelse',
    'shipmentPriceLabel' => 'Kostnad',
    'shipmentIsFreeLabel' => 'Gratis forsendelse',
    'shipmentDateLabel' => 'Forsendelsesdato',
    'shipmentDateShortLabel' => 'Dato',
    'deleteShipmentTooltip' => 'Slett forsendelsesmetode',
    'shipmentAddedSuccessMessage' => 'Forsendelsesmetode ble lagt til',
    'shipmentsDeleteSuccessMessage' => 'Forsendelsesmetoden ble slettet',
    'shipmentUpdateSuccessMessage' => 'Forsendelsesmetoden er oppdatert',
    'addNewShipmentMethodBtnLabel' => 'Legg til ny metode',
    'saveOrderSuccessMessage' => 'Bestillinger ble lagret',
    'cancelOrderSuccessMessage' => 'Bestillingen ble kansellert',
    'addNewClubBtnLabel' => 'Legg til ny fagforening',
    'editClubBtnLabel' => 'Edit club data',
    'addNewUnionBtnLabel' => 'Legg til ny fagforening',
    'editUnionBtnLabel' => 'Edit union data',
    'clubEmailLabel' => 'Klubbens e-postadresse',
    'unionEmailLabel' => 'Unionens e-postadresse',
    'clubNameLabel' => 'Klubbnavn',
    'unionNameLabel' => 'Unionens navn',
    'deleteClubTooltip' => 'Slett birøkterklubben',
    'deleteUnionTooltip' => 'Slett birøkterforbundet',
    'clubAddedSuccessMessage' => 'Klubben ble lagt til',
    'unionAddedSuccessMessage' => 'Forbundet ble lagt til',
    'clubsDeleteSuccessMessage' => 'Klubben ble slettet',
    'unionsDeleteSuccessMessage' => 'forbundet slettet',
    'clubUpdateSuccessMessage' => 'klubben ble oppdatert',
    'unionUpdateSuccessMessage' => 'forbundet ble oppdatert',
    'clubsCardSubtitle' => 'Birøkterklubber brukes i tilfelle kundeordre behandles i birøkterklubben. Hver klubb kan tildeles en forbund',
    'unionsCardSubtitle' => 'Birøkterforeninger benyttes i tilfelle kundeordre behandles innenfor birøkterforbundet.',
    'unions404Subtitle' => 'Listen er tom, du kan legge til første oppføring ved å klikke på en knapp nederst i høyre hjørne.',
    'shipmentCardSubtitle' => 'Du kan spesifisere flere forsendelsesmetoder for bestillingen din. Du kan for eksempel legge til klassisk postforsendelse eller henting på stedet.',
    'productNameLabel' => 'Produkt navn',
    'productCodeLabel' => 'Product kode',
    'productRegularPriceLabel' => 'Normal pris',
    'productBulkPriceLabel' => 'Bulk pris',
    'productPriceShortLabel' => 'Pris',
    'productSumShortLabel' => 'Sum',
    'productTypeLabel' => 'Katogori',
    'productTypeQueen' => 'Dronning',
    'productTypeOther' => 'Andre',
    'settingsProductsTitle' => 'Dine produkter',
    'productsCardSubtitle' => 'Du kan spesifisere flere produkter som vil være tilgjengelige i bigården din.',
    'deleteProductTooltip' => 'Slett Produkt',
    'addNewProductBtnLabel' => 'Legg til ny produkt',
    'editNewProductBtnLabel' => 'Edit product',
    'defineNewProductBtnLabel' => 'Definer ny produkt',
    'productAddedSuccessMessage' => 'Produktet ble lagt til',
    'productsDeleteSuccessMessage' => 'Produktet ble slettet',
    'productUpdateSuccessMessage' => 'Produktet ble oppdatert',
    'clientDisplayNameLabel' => 'Kunde navn',
    'clientFirstNameLabel' => 'Fornavn',
    'clientLastNameLabel' => 'Etternavn',
    'clientPhoneLabel' => 'Telefon',
    'clientPhoneShortLabel' => 'Tlf',
    'clientEmailLabel' => 'E-Post',
    'clientAddressLabel' => 'Address',
    'clientsDeleteSuccessMessage' => 'Klienten ble slettet',
    'clientsCreatedSuccessMessage' => 'Klienten ble lagt til',
    'clientsUpdatedSuccessMessage' => 'Klienten ble redigert',
    'client' => [
        'active_info' => 'Active clients are visible in the system, allowing you to use them in selected orders or for filtering. We will hide inactive entries from the application but make them visible for reports and archived orders.',
    ],
    'fabAddClientTooltip' => 'Legg til ny klient',
    'fabClientEditTitle' => 'Rediger klient',
    'fabClientChangeTitle' => 'Legg til og erstatt klient',
    'clientBasicDataTitle' => 'Grunnleggende data',
    'clientAddressDataTitle' => 'Leveringsadressedata',
    'inputAddressStreetLabel' => 'Gate',
    'inputAddressBuildingNumberLabel' => 'Husnummer',
    'inputAddressApartmentNumberLabel' => 'Leilighet nummer',
    'inputAddressPostCodeLabel' => 'Postnummer',
    'inputAddressCityLabel' => 'By',
    'searchByLabel' => 'Søk etter kunder',
    'searchOrdersByLabel' => 'Søk etter bestillinger',
    'searchShipmentsByLabel' => 'Søk etter forsendelser',
    'searchOrdersHintLabel' => 'Du kan søke på ordrenummer, kundenavn, telefon, e-postadresse eller på birøkterforeningens navn',
    'clientOrderClubLabel' => 'Klient birøkter forbund',
    'clientOrderClubLabelShort' => 'Birøkterklubb',
    'clientOrderClubLabelSuperShort' => 'Klubb',
    'clientOrderUnionLabelShort' => 'Birøkter forbundet',
    'clientOrderUnionLabelSuperShort' => 'Forbund',
    'clientCommentLabel' => 'Kommentar',
    'clientWarningLabel' => 'Samarbeids status',
    'clientAdditionalDataTitle' => 'Ytterligere data',
    'clientCommentsTitle' => 'Kunde samarbeids informasjon',
    'clientCooperationNullLabel' => 'Helt fint',
    'clientCooperationWarningLabel' => 'Advarsel',
    'clientCooperationBlockListLabel' => 'Blokkeringsliste',
    'notes' => 'Notater',

    // Orders
    'fabAddOrderTooltip' => 'Legg til ny ordre',
    'detailsPageTitle' => 'Ordre',
    '404Subtitle' => 'Ordren du prøver å nå finnes ikke i systemet vårt.',
    'detailsPageBackBtnLabel' => 'Bestillingsliste',
    'lastUpdatedLabel' => 'Sist oppdatert',
    'createdLabel' => 'Opprettet',
    'createdAtLabel' => 'Opprettet',
    'client' => [
        'cardTitle' => 'Hovedklient',
    ],
    'productsDataTitle' => 'Produkter',
    'shipmentsDataTitle' => 'Forsendelse',
    'shipmentsDayTitle' => 'Forsendelsesdag',
    'refundDetailsDataTitle' => 'Refusjon',
    'shipmentDetailsDataTitle' => 'Forsendelse detaljer',
    'orderDataTitle' => 'Ordre detaljer',
    'orderTypeLabel' => 'Refundert ordre',
    'orderTypeShortLabel' => 'Refundert',
    'source' => [
        'label' => 'Bestillingskilde',
        'phone' => 'Telefon',
        'mail' => 'E-Post',
        'direct' => 'Direkt',
        'other' => 'Annen',
    ],
    'orderCommentLabel' => 'Kommenter bestillingen',
    'orderIsBulkLabel' => 'Bulk ordre',
    'orderIsConfirmedByClientLabel' => 'Bekreftet av klient',
    'orderIsConfirmedByClientShortLabel' => 'Bekreftelse',
    'orderIsNotConfirmedByClientLabel' => 'Ikke bekreftet av klienten',
    'orderIsRefundConfirmedLabel' => 'Refusjon bekreftet',
    'orderIsRefundNonConfirmedLabel' => 'Refusjon ikke bekreftet',
    'ordersDeleteSuccessMessage' => 'Bestillingen ble slettet',
    'shipmentConfirmedSuccessfully' => 'Forsendelsen ble bekreftet',
    'updateSuccessMessage' => 'Bestillingen ble oppdatert',
    'priceSummaryLabel' => 'Sum',
    'confirmBtnLabel' => 'Bekreft',
    'shipmentDateChangedSuccessfully' => 'Forsendelsesdatoen ble endret',
    'disableRefundLabel' => 'Deaktiver refusjon',
    'enableRefundLabel' => 'Aktiver refusjon',
    'duplicateOrderLabel' => 'Duplisere',

    //order status
    'statusHeadline' => 'Ordre status',
    'refundHeadline' => 'Refundert',
    'status_null' => '--',
    'status_draft' => 'Utkast',
    'status_new' => 'Ny',
    'status_confirmed' => 'Bekreftet',
    'status_unconfirmed' => 'Ubekreftet',
    'status_completed' => 'Fullført',
    'status_sent' => 'Sendt',
    'status_cancelled' => 'avbrutt',
    'status_prepared' => 'Pakket',
    'status_ready' => 'Klar',
    'status_active' => 'Aktiv',
    'status_paid' => 'Betalt',
    'status_all' => 'Alle',
    'cancelBtnLabel' => 'Kanseller denne bestillingen',

    //Client details
    'clientLabel' => 'Klient',
    'clientPayingLabel' => 'Betaler',
    'queenReceiverLabel' => 'Direkte ordremottaker',
    'invoiceLabel' => 'Fakturering',
    'clientSearchPlaceholder' => 'Begynn å skrive for å søke etter klienter',
    'clubSearchPlaceholder' => 'Begynn å skrive for å søke etter forbundet',
    'noDataForClientSearch' => 'Ingen resultater',

    //Product detals
    'productLabel' => 'Produkter',
    'productSearchPlaceholder' => 'Begynn å skrive for å søke etter et produkt',
    'productCountLabel' => 'Telle',
    'productCodeLabel' => 'Code',
    'productPriceShortLabel' => 'Price',
    'productSumShortLabel' => 'Value',
    'showAdvancedBtnLabel' => 'Avansert',
    'productRefundedLabel' => 'Refundert',
    'advancedSettingsTitle' => 'Avanserte innstillinger',
    'otherDataTitle' => 'Annen',
    'unionSearchPlaceholder' => 'Begynn å skrive for å søke etter en fagforening',
    'noDateSetLabel' => 'Ingen dato satt ennå',

    //Queen Types
    'productQueenType' => [
        'label' => 'Dronning type i system',
        'label_short' => 'Dronning type',
        'tooltip_info' => 'Matching the product with queen type used in our system can help us to connect your product with our forecasting.',
        'null' => '--',
        'nu' => 'Jomfru dronning',
        'un' => 'Inseminert naturlig',
        'us' => 'Inseminert kunstig',
        'uss' => 'Inseminert kunstig med bekreftet yngel',
        'nucs' => 'Skaksverm',
        'cell' => 'Queen cell',
    ],

    //Shipments
    'addNewShipmentBtnLabel' => 'Legg til ny forsendelse',
    'deleteShipmentSuccessMessage' => 'Forsendelsen ble fjernet',
    'addShipmentSuccessMessage' => 'Forsendelsen ble lagt til',
    'showClientInformation' => 'Bytt klient',
    'shipmentClientLabel' => 'Mottaker',
    'shipmentClientShortLabel' => 'Mottaker',
    'shipmentSentLabel' => 'Send',
    'shipmentWaitingLabel' => 'Venter',
    'shipmentSentLongLabel' => 'Sending sendt',
    'shipmentPreparedLabel' => 'Forberedt',
    'shipmentPreparedLongLabel' => 'Forsendelse klargjort',
    'shipmentBasketLabel' => 'Produkter',
    'shipmentValueLabel' => 'Verdi',
    'shipmentSeeDetailsBtnLabel' => 'Se bestillingsdetaljer',
    'shipmentMethodLabel' => 'Metode',
    'shipmentNoDateTitle' => 'Forsendelsesdato ikke valgt',
    'shipmentTypeLabel' => 'Forsendelsestype',
    'isShipmentNumberGeneratedLabel' => 'Forsendelsesdokument generert',
    'shipmentNumberLabel' => 'Fraktnummer',

    //Client company data
    'clientCompanyDataTitle' => 'Bedriftsdata',
    'inputCompanyAddressLabel' => 'Adresse',
    'inputCompanyTaxNumberLabel' => 'Bedrifts mva nummer',
    'inputCompanyNameLabel' => 'Selskapets fulle navn',
    'inputCompanyPostCodeLabel' => 'Postnummer',
    'inputCompanyCityLabel' => 'Sted',
    'maskHint' => 'Skriv uten mellomrom eller bindestreker',

    //Shipment date proposition
    'shipmentDatePropTitle' => 'Velg forsendelsesdato',
    'shipmentDatePropShortTitle' => 'Velg dato',
    'chooseBtnLabel' => 'Lagre',
    'chooseBtnTooltip' => 'Valgt dag',
    'selectBtnLabel' => 'Velg',
    'todayBtnLabel' => 'I dag',
    'nextPeriodBtnLabel' => 'Neste måned',
    'prevPeriodBtnLabel' => 'Forrige måned',
    'addProductsToSeeLabel' => 'Legg til produkter for å angi en forsendelsesdato',
    'collapseShipmentDayCard' => 'Skjul kortet',
    'expandShipmentDayCard' => 'Utvid kortet',
    'prognosedLimitWarning' => 'Det er en mulighet for å overskride den anslåtte grensen for dronninger for den dagen',
    'prognosedLabel' => 'Prognostisert',
    'orderedLabel' => 'Bestilt',
    'differenceLabel' => 'Forskjell',

    //Queen insemination statuses
    'queen_vq' => 'JD',
    'queen_mq' => 'PD',
    'queen_ai' => 'NP',
    'queen_aib' => 'I',

    //Warnings
    'warning_headline' => 'Klientdata er ufullstendige',
    'warning_noClient' => 'Ingen klient er valgt',
    'warning_noPhone' => 'telefonen er ikke lagt til klienten',
    'warning_noAddressData' => 'adressedata er ufullstendige',

    //Invoice panel
    'invoicePreparedLabel' => 'Faktura klargjort for forsendelse',

    'table' => [
        'seasonHint' => 'fra :startDate to :endDate',
        'numberLabel' => 'Nummer',
        'statusLabel' => 'Status',
        'clientDisplayNameLabel' => 'Klient',
        'goToOrderBtnLabel' => 'Gå til detaljer',
        'progressLabel' => 'Fullstendighet',
        'seasonNullLabel' => 'Sesong: --',
        '404Subtitle' => 'Vi fant ingen bestillinger for kontoen din. Hvis du vil begynne, legg til første bestilling ved å bruke knappen nederst til høyre.',
        '404OrderTableSubtitle' => 'Det er ingen forsendelser funnet for denne bestillingen. Legg til første forsendelse for å begynne.',
        'queenLineLabel' => 'Linje',
        'shipment' => [
            'settingsLabel' => 'Forsendelse detaljer',
            'documentsLabel' => 'Forsendelsesdokumenter',
        ],
        '404NoShipmentForThisDay' => 'Det er ingen forsendelser planlagt i dag.',
        'but' => 'men',
        'goToOrders' => 'Gå til bestillinger',
        'noProductsInOrder' => 'Det er ingen produkter lagt til denne bestillingen',
    ],
    'child' => [
        'otherLabel' => 'Annen',
    ],
    'queenTypes' => [
        'nu' => 'JD',
        'un' => 'PD',
        'us' => 'NP',
        'uss' => 'I',
        'nucs' => 'SKAK',
    ],
    'files' => [
        'emptyTitle' => 'Vedlagte filer',
        'title' => 'Vedlagte filer (:value)',
        'addFile' => 'Legg til ny fil',
    ],
    'unions' => [
        'active' => 'Active',
        'inactive' => 'Union inactive',
        'active_info' => 'Active unions are visible in the system, allowing you to use them in selected orders or for filtering. We will hide inactive entries from the application but make them visible for reports and archived orders.',
    ],
    'unitTypes' => [
        'label' => 'Unit',
        'null' => '',
        'null_short' => '',
        'piece' => 'Piece',
        'piece_short' => 'Pc.',
        'set' => 'Set',
        'set_short' => 'set',
    ],
    'shipment' => [
        'payment_type' => 'Payment type',
        'payment_type_info' => 'Information about payment type can help us to connect this shipment with our invoicing functionality.',
        'cannotDeleteInfo' => 'We cannot delete this shipment as there are existing orders in our system. Please deactivate it if you want to hide it from future orders.',
    ],
    'paymentTypes' => [
        'null' => '--',
        'cash' => 'Cash',
        'cash_on_delivery' => 'Cash on delivery',
        'transfer' => 'Transfer',
        'card' => 'Card',
    ],
    'orderNumberingTypes' => [
        'null' => '--',
        'monthly' => 'Monthly',
        'yearly' => 'Yearly',
    ],
    'settings' => [
        'general' => [
            'title' => 'General settings',
            'subtitle' => 'Here you can find some general settings for your orders module.',
            'order_numbering_format' => 'Orders numbering format',
        ],
    ],
];
