<?php
return [
    'pageTitle' => 'Dronning serier',
    'pageSubtitle' => 'Du kan planlegge og administrere dronningserien i bigården din. Dronning Serier vil hjelpe deg med å planlegge aktiviteter før faktiske dronninger blir født.',
    'addSuccessMessage' => 'Ny serie ble lagt til.',
    'deleteSuccessMessage' => 'Serie :name ble slettet.',
    'updateSuccessMessage' => 'Serie :name ble oppdatert.',
    'transferredAtLabel' => 'Overføring av larve dato',
    'joinedAtLabel' => 'tiltredelsesdato',
    'isolatedAtLabel' => 'Isolasjonsdato',
    'bornAtLabel' => 'Født dato',
    'serieMaxCountLabel' => 'Forventet antall dronninger',
    'fabAddNewSerieTooltip' => 'Legg til ny serie',
    'newSerieInfoTitle' => 'Hva er serier for i vår applikasjon?',
    'newSerieInfoDesc' => 'Med serier kan du planlegge bedre fra det øyeblikket larver flyttes til det tidspunktet da dronninger blir født i klekkeskapet. Opprettede serier sammenlignes med salgsprognose basert på dine bestillinger, og gir deg innspill om hvor mange bestillinger du kan håndtere i løpet av sesongen.',
    'serieNameLabel' => 'Serie navn',
    'manualEfficiencyLabel' => 'Bruk standard effektivitetssett',
    'editSerieModalTitle' => 'Rediger serien',
    'startDateLabel' => 'Start dato',
    'endDateLabel' => 'Slutt dato',
    'addMultipleSerieSuccessMessage' => 'Serier ble lagt til',
    'addMultipleSeriesModalHivesPrefixLabel' => 'Prefiks for serienavn',
    'addMultipleSeriesModalTitle' => 'Legg til flere serier',
    'addMultipleSeriesModalInfoBoxTitle' => 'Laget serieoversikt',
    'noHivesInfoBox' => 'Fyll inn start- og sluttdatoen for å se eksempler på opprettede serier.',
    'saveOnlyThisSerieLabel' => 'Endre kun denne',
    'saveAllSeriesThisLabel' => 'Endre denne og neste serie',
    'revealSerieTitle' => 'Liste over serier',
    'revealSerieSubtitle' => 'Denne serien ble laget i et sett med andre serier. Vil du endre datoene også for neste serie fra listen?',
    'defaultEfficiencyInfo' => 'Som standard bruker serien en dynamisk beregning av effektiviteten til hvert trinn. Hvis du vil tvinge frem bruken av standardverdier, merk av for dette alternativet.',

    //Statistics
    'lostBornCountLabel' => 'Antall: mistet under fødselen',
    'joinedCountLabel' => 'Antall: sluttet seg til',
    'isolatedCountLabel' => 'Antall: isolert',
    'transferredCountLabel' => 'Antall: overførte larver',
    'realCountLabel' => 'Virkelig antall fødte dronninger',
    'prognosedCountLabel' => 'Prognostisert antall fødte dronninger',
    'efficiencyLabel' => 'Effektivitet',
    'efficiencyJoinedLabel' => 'Effektivitet',

    'workCardTitle' => 'Dronning serier',
    'workCardInfoTitle' => 'Hva brukes dette panelet til?',
    'workCardSubTitle' => 'Hvis du bruker dronningsserier i applikasjonen vår - i dette panelet finner du serien som krever din handling i dag. Data gitt her brukes for prognose hvor mye dronninger som er tilgjengelighet.',
    'day_transferred' => 'Overføringsdag',
    'day_joined' => 'Dag ført sammen',
    'day_isolated' => 'Isolasjonsdag',
    'day_born' => 'Fødselsdag',
    'allGoodText' => 'Alt bra her! Det er ingenting å jobbe med her i dag eller alle oppgavene var allerede fullført',

];
