<?php
return [
    'nav' => [
        'apiaryLabel' => 'Birgård',
        'apiaryLogo' => 'Logo',
        'teamLabel' => 'Team',
        'queenLinesLabel' => 'Dronning linjer',
        'seasonsLabel' => 'Sesong',
    ],
    'general' => [
        'pageTitle' => 'Innstillinger',
        'subTitle' => 'Du kan administrere bigårdsinnstillingene dine her.',
    ],
    'apiary' => [
        'cardTitle' => 'Bigårds detaljer',
    ],
    'efficiency' => [
        'cardTitle' => 'Effektivitets innstillinger',
    ],
    'queenLines' => [
        'cardTitle' => 'Dronning linjer',
        'subTitle' => 'Du kan administrere dronningelinjene dine her.
                            <br/>Hvis du ikke lenger trenger en dronning linje, kan du enten slette den eller deaktivere den i applikasjonen.',
    ],
    'seasons' => [
        'cardTitle' => 'Sesong',
        'cardTitleSingular' => 'Sesong',
        'subTitle' => 'Årstider lar deg dele opp bestillinger og aktiviteter i bigården i definerte perioder. Du kan legge til nye sesonger i fortid og fremtid, og vi vil prøve å matche deler av applikasjonen til sesongsettet.',
        'nameLabel' => 'Navn',
        'startDateLabel' => 'Start dato',
        'endDateLabel' => 'Slutt dato',
        '404Subtitle' => 'Det er ingen definerte sesonger ennå, vennligst legg til først for å starte.',
        'addSuccessMessage' => 'Sesongen ble lagt til.',
        'updateSuccessMessage' => 'Sesongen ble oppdatert.',
        'deleteSuccessMessage' => 'Sesong :name ble slettet.',
        'editModalTitle' => 'Rediger sesong :name',
        'addModalTitle' => 'Legg til ny sesong',
    ],
    'queenLinesNameLabel' => 'Kort navn',
    'queenLinesFullNameLabel' => 'Fullt navn',
    'queenLinesNameLabelShort' => 'Linje',
    'allQueenLinesLabel' => 'Alle linjer',
    'beeSubspeciesNameLabel' => 'Underart',
    'queenLineActiveNameLabel' => 'Aktiv',
    'clubActiveNameLabel' => 'Aktiv',
    'unionActiveNameLabel' => 'Aktiv',
    'queenLineNotActiveNameLabel' => 'Inaktiv',
    'clubNotActiveNameLabel' => 'Inaktiv',
    'a_m_mellifera' => 'A. m. mellifera',
    'a_m_carnica' => 'A. m. Krainer',
    'a_m_caucasica' => 'A. m. Kaukasisk',
    'a_m_ligustica' => 'A. m. ligustica',
    'queen_lines' => [
        'a_m_mellifera' => 'A. m. mellifera',
        'a_m_carnica' => 'A. m. Krainer',
        'a_m_caucasica' => 'A. m. Kaukasisk',
        'a_m_ligustica' => 'A. m. ligustica',
    ],
    'crossbreed' => 'Kryssning',
    'hybrid' => 'Hybrid',
    'deleteQueenLineSuccessMessage' => 'Dronning linje :name ble slettet',
    'queenLineUpdateSuccessMessage' => 'Dronning linje :name ble oppdatert',
    'queenLineAddedSuccessMessage' => 'Dronning linje :navn ble lagt til',
    'addNewQueenLineBtnLabel' => 'Legg til ny dronning linje',
    'deleteQueenLineTooltip' => 'Slett denne dronningslinjen',
    'deleteQueenLineInfoTooltip' => 'Denne linjen er alene eller har minst én eksisterende dronning i systemet vårt. Derfor kan vi ikke slette den. I stedet kan du deaktivere den, og den vil ikke være synlig i applikasjonen vår.',
    'apiarySettingsPageTitle' => 'Bigårds innstillinger',
    'apiarySettingsSubtitle' => 'Du kan administrere bigårdsinnstillingene dine her.',
    'apiaryCardTitle' => 'Hovedinnstillinger',
    'globalEfficiencyLabel' => 'Global effektivitet',
    'globalEfficiencyHint' => 'Global effektivitet brukes når lokasjonseffektiviteten ennå ikke kan beregnes.',
    'seriesEfficiencyLabel' => 'Serieeffektivitet',
    'seriesIsolationEfficiencyLabel' => 'Serie lukkede celler effektivitet',
    'seriesBornEfficiencyLabel' => 'Serie født effektivitet',
    'seriesEfficiencyHint' => 'Serieeffektivitet brukes for prognoseberegning - som startverdi.',
    'updatedSuccess' => 'Settings were updated successfully',

    'invoice' => [
        'cardTitle' => 'Faktureringsdetaljer',
        'inputAddressStreetLabel' => 'Gate',
        'inputAddressBuildingNumberLabel' => 'Hus nummer',
        'inputAddressApartmentNumberLabel' => 'Leilighets nummer',
        'inputAddressPostCodeLabel' => 'Postnummer',
        'inputAddressCityLabel' => 'By',
        'companyNameLabel' => 'Firma navn',
        'inputVatNumberLabel' => 'VAT number',
        'inputVatNumberShortLabel' => 'MVA',
        'noInvoiceDataWarning' => 'Faktureringsdata er ufullstendige',
        'nrbLabel' => 'Bank konto',
    ],
    'contact' => [
        'cardTitle' => 'Kontakt detaljer',
        'inputContactEmailLabel' => 'E-Post',
        'inputContactPhoneLabel' => 'Telefon',
    ],
    'apiaryLogo' => [
        'cardTitle' => 'Firma logo',
        'cardSubTitle' => 'Du kan laste opp din tilpassede firmalogo. Vi kan bruke det i genererte pdf-filer og i applikasjonslayout.',
        'uploadForm' => [
            'cardTitle' => 'Last opp ny logo',
            'cardSubTitle' => 'Filrestriksjoner: størrelse maks 500 kB, format: png, jpg, jpeg.',
            'inputFile' => 'Velg fil',
        ],
    ]
];
