<?php
return [
    'accountAppName' => 'Konto',
    'apiaryAppName' => 'Min bigård',
    'clubAppName' => 'Klubb',
    'queensAppName' => 'Dronning avlede',
    'logoutBtnLabel' => 'Logg ut',
    'createdBy' => 'Laget av',
    'createdAt' => 'Opprettet kl',
    'workInProgessHeadline' => 'Arbeid pågår.',
    'workInProgessSubheadline' => 'Våre hardtarbeidende bier jobber med å gjøre forbedringer her. Kom tilbake snart!',
    'placeholderTitle' => 'Eksempel på sidetittel',
    'cancelBtnLabel' => 'Avbryt',
    'closeBtnLabel' => 'Lukk',
    'saveBtnLabel' => 'Lagre',
    'addBtnLabel' => 'Legg til',
    'deleteBtnLabel' => 'Slett',
    'printBtnLabel' => 'Print',
    'filterBtnLabel' => 'Filter',
    'confirm' => 'Vennligst bekreft:',
    'search' => 'Søk',
    'goBack' => 'Gå tilbake',
    'new' => 'Ny',
    'owner' => 'Eier',
    'noResults' => 'Ingen resultater å vise',
    'partnerPszczelarzaURI' => 'https://partnerpszczelarza.pl',
    'today' => 'idag',
    'loadingDataMsg' => 'Laster inn data...',
    'continueBtnLabel' => 'Neste steg',
    'savencontinueBtnLabel' => 'Lagre og fortsett',
    'detailsBtnLabel' => 'Detaljer',
    'editBtnLabel' => 'Redigere',
    'moveBtnLabel' => 'Flytte',
    'showBtnLabel' => 'Se detaljer',
    'errorOccurredMessage' => 'Det oppsto en feil under denne handlingen, prøv igjen.',
    'getBackToHomepageBtnLabel' => 'Gå tilbake til startsiden',
    '401AltTitle' => 'Uautorisert!',
    '401Title' => 'Oops!',
    '401Subtitle' => 'Det ser ut til at du ikke har rettigheter til å se denne siden. <br/>Ta kontakt med kontoeieren for å finne en løsning.',
    'onLabel' => 'På',
    'offLabel' => 'Av',
    'archiveBtnLabel' => 'Arkiv',
    '404Title' => 'Det er tomt her!',
    '404Subtitle' => 'Vi har ikke noe å vise her ennå.',
    'undefinedLabel' => 'Ikke funnet',
    'scrollToTopLabel' => 'Tilbake til toppen',
    'dataTable' => [
        'allOptionLabel' => 'Alle',
        'rowsPerPageLabel' => 'Rader per side',
        'pageText' => '{0}-{1} of {2}',
    ],
    'accept' => 'Aksepterer',
    'reject' => 'Avvis',
    'true' => 'Ja',
    'false' => 'Nei',
    'copy' => '-kopiere',
    'uploadBtn' => 'Laste opp',
    'chooseBtn' => 'Velg',
    'downloadBtn' => 'Last ned',
    'optionalFields' => 'Valgfrie felter',
    'goToSubscriptionPageBtn' => 'Oppgrader kontoen din',
    'actionsLabel' => 'Handlinger',
    'orText' => 'eller',
    'links' => [
        'documentation' => [
            'text' => 'Dokumentasjon',
            'href' => 'https://partnerpszczelarza.pl/aplikacja-hodowcy/dokumentacja/',
        ],
        'privacyPolicy' => [
            'text' => 'Personvernerklæring',
            'href' => 'https://partnerpszczelarza.pl/polityka-prywatnosci',
        ],
    ],
    'refreshBtn' => 'Forfriske',

    // time
    'today' => 'today',
    'thisWeek' => 'this week',
    'thisMonth' => 'this month',
    'thisYear' => 'this year',
    'customDateRange' => 'custom dates',
    'from' => 'from',
    'to' => 'to',
    'dataTable' => [
        'allOptionLabel' => 'All',
        'rowsPerPageLabel' => 'Rows per page',
        'pageText' => '{0}-{1} of {2}',
    ],
];
