<?php

return [
    'pageTitle' => 'Partie matek pszczelich',
    'pageSubtitle' => 'Partie matek są wykorzystywane na stronie lokalizacji do szybkiego dodawania matek do uli. Na tej stronie możesz zarządzać partiami, udostępniać je dla poszczególnych lokalizacji oraz obserwować statystyki każdej partii.',
    'lineLabel' => 'Linia',
    'confirmedLabel' => '{0} potwierdzonych przeglądami|{1} potwierdzona przeglądem|[2,4] potwierdzone przeglądami|[5,*] potwierdzonych przeglądami',
    'potentiallyBroodingLabel' => '{0} potencjalnie czerwiących|{1} potencjalnie czerwiąca|[2,4] potencjalnie czerwiące|[5,*] potencjalnie czerwiących',
    'virginQueensLabel' => '{0} nieunasienionych|{1} nieunasieniona|[2,4] nieunasienione|[5,*] nieunasienionych',
    'cellQueensLabel' => '{0} mateczników |{1} matecznik |[2,4] mateczniki |[5,*] mateczników',
    'nameLabel' => 'Nazwa partii',
    'daysOfLifeLabel' => 'Dni życia',
    'cycleLengthLabel' => 'Długość cyklu',
    'serieLabel' => 'Seria',
    'weeksLabel' => 'tygodnie',
    'soldLabel' => 'sprzedanych',
    'lostLabel' => 'utraconych',
    'efficiencyLabel' => 'wydajność',
    'fabAddNewTooltip' => 'Dodaj nową partię',
    'editBatchLabel' => 'Edytuj partię',
    'efficiencyTooltip' => 'Wydajność będzie widoczna jeżeli ilość matek sprzedanych, utraconych oraz potwierdzonych przeglądami przekroczy 25% wielkości partii.',
    'infoTitle' => 'Do czego mogę wykorzystać partie matek?',
    'infoDescription' => 'Partie matek mogą być częścią serii matek, pozwalają na szybkie dodawanie matek do uli w lokalizacjach. Możesz stworzyć partię dla poszczególnych lokalizacji oraz linii hodowlanych. Wraz z upływem czasu pojawią się statystyki dla każdej partii.',
    'addSuccessMessage' => 'Nowa partia została pomyślnie dodana!',
    'deleteSuccessMessage' => 'Partia została pomyślnie usunięta.',
    'updateSuccessMessage' => 'Partia :name została pomyślnie uaktualniona.',
    'modal' => [
        'table' => [
            'headline' => 'Przypisane limity dla lokalizacji',
            'locations' => 'Lokalizacja',
            'emptyHives' => 'Puste ule',
            'disposed' => 'Rozdane z partii',
            'limit' => 'Limit na lokalizację',
        ],
    ],
    'locationShortLabel' => 'Lokalizacja',
    'disposedShortLabel' => 'Aktualnie rozdane z partii',
    'limitShortLabel' => 'Ilość',
    'emptyHives' => '{0} pustych uli|[1,4] puste ule|[5,*] pustych uli',
    'type' => [
        'label' => 'Partia oparta o',
        'queen' => 'Wygryzione matki',
        'cells' => 'Mateczniki',
    ],
];
