<?php
return [
    'mainPageTitle' => 'Lista zamówień',
    'mainPageSubtitle' => 'Możesz zarządzać swoimi zamówieniami. Zamówienia usunięte lub zakończone są widoczne na osobnej liście.',
    'clientsPageTitle' => 'Twoi klienci',
    'clientsPageSubtitle' => 'Na tej stronie możesz zarządzać danymi Twoich klientów. Każdy z dodanych klientów będzie dostępny również w sekcji zamówień.',
    'shipmentPageTitle' => 'Wysyłki',
    'shipmentPageSubtitle' => 'Na tej stronie możesz zarządzać wysyłkami do Twoich zamówień. ',
    'settingsPageTitle' => 'Ustawienia sklepu',
    'settingsPageSubtitle' => 'Na tej stronie możesz zmieniać ustawienia modułu zamówień. Możesz zarządzać swoim produktami, listą związków pszczelarskich oraz metodami wysyłki.',
    'statsPageTitle' => 'Statystyki zamówień',
    'statsPageSubtitle' => 'Możesz tu sprawdzić statystyki zamówień',
    'settingsProductTitle' => 'Produkty',
    'settingsClubsTitle' => 'Koła pszczelarskie',
    'settingsClubsSingleTitle' => 'Koło pszczelarskie',
    'settingsUnionsTitle' => 'Związki pszczelarskie',
    'settingsUnionsSingleTitle' => 'Związek pszczelarski',
    'settingsShippingTitle' => 'Metody wysyłki',
    'defaultLabel' => 'Domyślna',
    'shipmentNameLabel' => 'Nazwa',
    'shipmentPriceLabel' => 'Koszt',
    'shipmentIsFreeLabel' => 'Darmowa wysyłka',
    'shipmentDateLabel' => 'Data wysyłki',
    'shipmentDateShortLabel' => 'Data',
    'deleteShipmentTooltip' => 'Usuń metodę wysyłki',
    'shipmentAddedSuccessMessage' => 'Pomyślnie dodano metodę wysyłki',
    'shipmentsDeleteSuccessMessage' => 'Pomyślnie usunięto metodę wysyłki',
    'shipmentUpdateSuccessMessage' => 'Pomyślnie zmieniono metodę wysyłki',
    'addNewShipmentMethodBtnLabel' => 'Dodaj nową metodę wysyłki',
    'saveOrderSuccessMessage' => 'Zamówienie zostało zapisane',
    'cancelOrderSuccessMessage' => 'Zamówienie zostało anulowane',
    'addNewClubBtnLabel' => 'Dodaj nowe koło',
    'editClubBtnLabel' => 'Edytuj koło',
    'addNewUnionBtnLabel' => 'Dodaj nowy związek',
    'editUnionBtnLabel' => 'Edytuj dane związku',
    'clubEmailLabel' => 'Adres email koła',
    'unionEmailLabel' => 'Adres email związku',
    'clubNameLabel' => 'Nazwa koła',
    'unionNameLabel' => 'Nazwa związku',
    'deleteClubTooltip' => 'Usuń koło pszczelarskie',
    'deleteUnionTooltip' => 'Usuń związek pszczelarski',
    'clubAddedSuccessMessage' => 'Pomyślnie dodano koło pszczelarskie',
    'unionAddedSuccessMessage' => 'Pomyślnie dodano związek pszczelarski',
    'clubsDeleteSuccessMessage' => 'Pomyślnie usunięto koło pszczelarskie',
    'unionsDeleteSuccessMessage' => 'Pomyślnie usunięto związek pszczelarski',
    'clubUpdateSuccessMessage' => 'Pomyślnie zmieniono koło pszczelarskie',
    'unionUpdateSuccessMessage' => 'Pomyślnie zmieniono związek pszczelarski',
    'clubsCardSubtitle' => 'Lista kół pszczelarskich będzie wykorzystana w przypadku zamówień refundowanych. Możesz wprowadzić adres email aby wysyłać raporty bezpośrednio na adres koła.',
    'unionsCardSubtitle' => 'Lista związków pszczelarskich będzie wykorzystana w przypadku zamówień rozliczanych przez związki. Możesz wprowadzić adres email aby wysyłać raporty bezpośrednio na adres związku.',
    'unions404Subtitle' => 'Lista związków pszczelarskich jest pusta, możesz dodać pierwszy wpis klikając w przycisk w prawym dolnym rogu ekranu.',
    'clubs404Subtitle' => 'Lista klubów pszczelarskich jest pusta, możesz dodać pierwszy wpis klikając w przycisk w prawym dolnym rogu ekranu.',
    'shipmentCardSubtitle' => 'Możesz zdefiniować wiele metod wysyłki, które później będą użyte przy tworzeniu zamówienia. Dla przykładu metodą wysyłki może być klasyczna paczka lub odbiór osobisty w wybranej lokalizacji.',
    'settingsProductsTitle' => 'Twoje produkty',
    'productsCardSubtitle' => 'Możesz zdefiniować wiele produktów w Twojej pasiece, będą one dostępne do wyboru na karcie zamówienia',
    'deleteProductTooltip' => 'Usuń produkt',
    'addNewProductBtnLabel' => 'Dodaj produkt',
    'editNewProductBtnLabel' => 'Edytuj produkt',
    'defineNewProductBtnLabel' => 'Stwórz nowy produkt',
    'productAddedSuccessMessage' => 'Pomyślnie dodano produkt',
    'productsDeleteSuccessMessage' => 'Pomyślnie usunięto produkt',
    'productUpdateSuccessMessage' => 'Pomyślnie zmieniono dane produktu',
    'clientDisplayNameLabel' => 'Imię i nazwisko',
    'clientFirstNameLabel' => 'Imię',
    'clientLastNameLabel' => 'Nazwisko',
    'clientPhoneLabel' => 'Telefon',
    'clientPhoneShortLabel' => 'Tel',
    'clientEmailLabel' => 'E-mail',
    'clientAddressLabel' => 'Adres',
    'clientsDeleteSuccessMessage' => 'Pomyślnie usunięto klienta z aplikacji',
    'clientsCreatedSuccessMessage' => 'Pomyślnie dodano klienta',
    'clientsUpdatedSuccessMessage' => 'Pomyślnie edytowane dane klienta',
    'client' => [
        'active_info' => 'Aktywni klienci są widoczni w naszej aplikacji, dzięki czemu możesz z nich korzystać w zamówieniach, raportach i filtrach. Nieaktywne wpisy ukryjemy, natomiast dalej będą dostępne dla archiwalnych raportów i zamówień.',
    ],
    'fabAddClientTooltip' => 'Dodaj nowego klienta',
    'fabClientEditTitle' => 'Edytuj dane klienta',
    'fabClientChangeTitle' => 'Dodaj i zastąp klienta',
    'clientBasicDataTitle' => 'Podstawowe dane',
    'clientAddressDataTitle' => 'Dane adresowe do wysyłki',
    'inputAddressStreetLabel' => 'Ulica \ Miejscowość',
    'inputAddressBuildingNumberLabel' => 'Numer domu',
    'inputAddressApartmentNumberLabel' => 'Numer mieszkania',
    'inputAddressPostCodeLabel' => 'Kod pocztowy',
    'inputAddressCityLabel' => 'Miasto \ Poczta',
    'searchByLabel' => 'Szukaj wśród klientów',
    'searchOrdersByLabel' => 'Szukaj w zamówieniach',
    'searchShipmentsByLabel' => 'Szukaj w wysyłkach',
    'searchOrdersHintLabel' => 'Możesz szukać po numerze zamówienia, nazwisku klienta, numerze telefonu, adresie email lub nazwie koła pszczelarskiego',
    'clientOrderClubLabel' => 'Związek pszczelarski klienta',
    'clientOrderClubLabelShort' => 'Koło pszczelarskie',
    'clientOrderClubLabelSuperShort' => 'Koło',
    'clientOrderUnionLabelShort' => 'Związek',
    'clientOrderUnionLabelSuperShort' => 'Związek',
    'clientCommentLabel' => 'Komentarz',
    'clientWarningLabel' => 'Status współpracy',
    'clientAdditionalDataTitle' => 'Dodatkowe dane klienta',
    'clientCommentsTitle' => 'Informacje o współpracy z klientem',
    'clientCooperationNullLabel' => 'Brak uwag',
    'clientCooperationWarningLabel' => 'Ostrzeżenie',
    'clientCooperationBlockListLabel' => 'Czarna lista',
    'notes' => 'Notatki',

    // Orders
    'fabAddOrderTooltip' => 'Dodaj nowe zamówienie',
    'detailsPageTitle' => 'Zamówienie',
    '404Subtitle' => 'Nie znaleźliśmy tego zamówienia w naszym systemie',
    'detailsPageBackBtnLabel' => 'Lista zamówień',
    'lastUpdatedLabel' => 'Ostatnia aktualizacja',
    'createdLabel' => 'Utworzone',
    'createdAtLabel' => 'Data złożenia zamówienia',
    'client' => [
        'cardTitle' => 'Główny klient',
    ],
    'productsDataTitle' => 'Produkty',
    'shipmentsDataTitle' => 'Wysyłka',
    'shipmentsDayTitle' => 'Wysyłka',
    'refundDetailsDataTitle' => 'Dane do refundacji',
    'shipmentDetailsDataTitle' => 'Szczegóły wysyłki',
    'orderDataTitle' => 'Szczegóły zamówienia',
    'orderTypeLabel' => 'Zamówienie refundowane',
    'orderTypeShortLabel' => 'Refundacja',
    'source' => [
        'label' => 'Źródło zamówienia',
        'phone' => 'Telefon',
        'mail' => 'E-mail',
        'direct' => 'Bezpośrednie',
        'other' => 'Inne',
    ],
    'orderCommentLabel' => 'Komentarz',
    'orderIsBulkLabel' => 'Zamówienie hurtowe',
    'orderIsConfirmedByClientLabel' => 'Wysyłka potwierdzona',
    'orderIsConfirmedByClientShortLabel' => 'Potwierdzenie',
    'orderIsNotConfirmedByClientLabel' => 'Wysyłka niepotwierdzona',
    'orderIsRefundConfirmedLabel' => 'Refundacja potwierdzona',
    'orderIsRefundNonConfirmedLabel' => 'Refundacja niepotwierdzona',
    'ordersDeleteSuccessMessage' => 'Zamówienie zostało usunięte',
    'shipmentConfirmedSuccessfully' => 'Wysyłka została potwierdzona',
    'updateSuccessMessage' => 'Pomyślnie zapisaliśmy zmiany.',
    'priceSummaryLabel' => 'Produkty razem',
    'confirmBtnLabel' => 'Potwierdź',
    'shipmentDateChangedSuccessfully' => 'Data wysyłki została zmieniona',
    'disableRefundLabel' => 'Wyłącz refundację',
    'enableRefundLabel' => 'Włącz refundację',
    'duplicateOrderLabel' => 'Duplikuj',

    //order status
    'statusHeadline' => 'Status',
    'refundHeadline' => 'Refundacja',
    'status_null' => '--',
    'status_draft' => 'Szkic',
    'status_new' => 'Nowe',
    'status_confirmed' => 'Potwierdzona',
    'status_unconfirmed' => 'Niepotwierdzona',
    'status_completed' => 'Zrealizowane',
    'status_sent' => 'Wysłane',
    'status_cancelled' => 'Anulowane',
    'status_prepared' => 'Spakowane',
    'status_ready' => 'Przygotowane',
    'status_active' => 'Aktywne',
    'status_paid' => 'Zapłacone',
    'status_all' => 'Wszystkie',
    'cancelBtnLabel' => 'Anuluj zamówienie',

    //Client details
    'clientLabel' => 'Klient',
    'clientPayingLabel' => 'Płatnik',
    'queenReceiverLabel' => 'Odbiorca na rozliczeniu',
    'invoiceLabel' => 'Rozliczenia',
    'clientSearchPlaceholder' => 'Zacznij pisać aby wyszukać klienta',
    'clubSearchPlaceholder' => 'Zacznij pisać aby wyszukać koło',
    'noDataForClientSearch' => 'Brak wyników',

    //Product detals
    'product' => [
        'name' => 'Nazwa',
        'code' => 'Kod produktu',
        'code_info' => 'Kod produktu powinien być unikalny i krótki. Pozwoli nam to odpowiednio przypisywać produkty do zamówień.',
        'net_price' => 'Cena netto',
        'vat' => 'VAT',
        'gross_price' => 'Cena brutto',
        'gross_price_hint' => 'obliczana automatycznie',
        'price_short' => 'Cena',
        'sum_short' => 'Suma',
        'gross_sum' => 'Kwota brutto',
    ],

    'productType' => [
        'label' => 'Kategoria',
        'tooltip_info' => 'Niektóre kategorie produktów możemy połączyć z działaniem aplikacji w module zamówień. Obecnie wspierane kategorie: matki.',
        'queen' => 'Matka',
        'other' => 'Inne',
    ],

    'vatTypes' => [
        'null' => 'zw.',
        '0' => '0%',
        '5' => '5%',
        '8' => '8%',
        '23' => '23%',
    ],

    'productLabel' => 'Produkt',
    'productSearchPlaceholder' => 'Zacznij pisać aby znaleźć produkt',
    'productCountLabel' => 'Liczba',
    'productCodeLabel' => 'Kod',
    'productPriceShortLabel' => 'Cena',
    'productSumShortLabel' => 'Wartość',
    'showAdvancedBtnLabel' => 'Zaawansowane',
    'productRefundedLabel' => 'Refundowane',
    'advancedSettingsTitle' => 'Zaawansowane ustawienia',
    'otherDataTitle' => 'Inne',
    'unionSearchPlaceholder' => 'Zacznij pisać, żeby wyszukać w związkach',
    'noDateSetLabel' => 'Brak ustawionej daty',
    'active_tooltip_info' => 'Aktywne produkty są widoczne w nowych zamówienia. Deaktywując produkt, schowasz go z widoku nowych zamówień.',

    //Queen Types
    'productQueenType' => [
        'label' => 'Powiązanie typu matki w systemie',
        'label_short' => 'Typ matki',
        'tooltip_info' => 'Połączenie produktu z typem matki pozwoli nam na lepsze wskazanie dostępnych produktów w panelu zamówień.',
        'null' => '--',
        'nu' => 'Nieunasieniona',
        'un' => 'Unasieniona naturalnie',
        'us' => 'Unasieniona sztucznie',
        'uss' => 'Unasieniona sztucznie z potwierdzonym czerwieniem',
        'nucs' => 'Odkład',
        'cell' => 'Matecznik',
    ],

    //Shipments
    'addNewShipmentBtnLabel' => 'Dodaj nową wysyłkę',
    'deleteShipmentSuccessMessage' => 'Wysyłka została usunięta',
    'addShipmentSuccessMessage' => 'Wysyłka została dodana',
    'showClientInformation' => 'Zmień klienta',
    'shipmentClientLabel' => 'Odbiorca przesyłki',
    'shipmentClientShortLabel' => 'Odbiorca',
    'shipmentSentLabel' => 'Wysłane',
    'shipmentWaitingLabel' => 'Oczekuje',
    'shipmentSentLongLabel' => 'Zamówienie wysłane',
    'shipmentPreparedLabel' => 'Przygotowane',
    'shipmentPreparedLongLabel' => 'Zamówienie przygotowane',
    'shipmentBasketLabel' => 'Produkty',
    'shipmentValueLabel' => 'Wartość',
    'shipmentSeeDetailsBtnLabel' => 'Przejdź do zamówienia',
    'shipmentMethodLabel' => 'Metoda',
    'shipmentNoDateTitle' => 'Wysyłki bez ustawionej daty',
    'shipmentTypeLabel' => 'Typ wysyłki',
    'isShipmentNumberGeneratedLabel' => 'Wygenerowano dokument wysyłki',
    'shipmentNumberLabel' => 'Numer przewozowy',

    //Client company data
    'clientCompanyDataTitle' => 'Dane firmy klienta',
    'inputCompanyAddressLabel' => 'Adres',
    'inputCompanyTaxNumberLabel' => 'NIP',
    'inputCompanyNameLabel' => 'Pełna nazwa firmy',
    'inputCompanyPostCodeLabel' => 'Kod pocztowy',
    'inputCompanyCityLabel' => 'Miasto',
    'maskHint' => 'Wpisz bez myślników i spacji',

    //Shipment date proposition
    'shipmentDatePropTitle' => 'Wybierz datę wysyłki',
    'shipmentDatePropShortTitle' => 'Zmień datę',
    'chooseBtnLabel' => 'Zapisz wybór',
    'chooseBtnTooltip' => 'Wybrany dzień',
    'selectBtnLabel' => 'Zaznacz dzień',
    'todayBtnLabel' => 'Dzisiaj',
    'nextPeriodBtnLabel' => 'Następny miesiąc',
    'prevPeriodBtnLabel' => 'Poprzedni miesiąc',
    'addProductsToSeeLabel' => 'Dodaj produkty, aby wybrać datę',
    'collapseShipmentDayCard' => 'Zwiń szczegóły',
    'expandShipmentDayCard' => 'Rozwiń szczegóły',
    'prognosedLimitWarning' => 'Istnieje ryzyko przekroczenia prognozowanej ilości zamówionych matek!',
    'prognosedLabel' => 'Prognozowane',
    'orderedLabel' => 'Zamówione',
    'differenceLabel' => 'Różnica',

    //Queen insemination statuses
    'queen_vq' => 'NU',
    'queen_mq' => 'UN',
    'queen_ai' => 'US',
    'queen_aib' => 'USS',

    //Warnings
    'warning_headline' => 'Dane klienta niekompletne',
    'warning_noClient' => 'Brak wybranego klienta',
    'warning_noPhone' => 'brak telefonu klienta',
    'warning_noAddressData' => 'niepełne dane adresowe',

    //Invoice panel
    'invoicePreparedLabel' => 'Faktura wystawiona dla wysyłki',

    'table' => [
        'seasonHint' => 'od :startDate do :endDate',
        'numberLabel' => 'Numer',
        'statusLabel' => 'Status',
        'clientDisplayNameLabel' => 'Klient',
        'goToOrderBtnLabel' => 'Przejdź do zamówienia',
        'progressLabel' => 'Stopień realizacji',
        'seasonNullLabel' => 'Sezon: --',
        '404Subtitle' => 'Nie znaleźliśmy żadnych zamówień dla Twojej pasieki. Aby rozpocząć, dodaj pierwsze zamówienie używając przycisku w dolnym prawym rogu.',
        '404OrderTableSubtitle' => 'Nie znaleźliśmy żadnych wysyłek. Aby rozpocząć, dodaj pierwszą wysyłkę.',
        'queenLineLabel' => 'Linia',
        'shipment' => [
            'settingsLabel' => 'Szczegóły wysyłki',
            'documentsLabel' => 'Dokumenty wysyłki',
        ],
        '404NoShipmentForThisDay' => 'Na dzisiaj nie zaplanowano żadnych wysyłek.',
        'but' => 'lub',
        'goToOrders' => 'Przejdź do zamówień',
        'noProductsInOrder' => 'Brak produktów w zamówieniu',
    ],
    'child' => [
        'otherLabel' => 'Inne',
    ],
    'queenTypes' => [
        'nu' => 'NU',
        'un' => 'UN',
        'us' => 'US',
        'uss' => 'USS',
        'nucs' => 'Odkład',
    ],
    'files' => [
        'emptyTitle' => 'Dodaj pliki do zamówienia',
        'title' => 'Dołączone pliki zamówienia (:value)',
        'addFile' => 'Dodaj nowy plik',
    ],
    'unions' => [
        'active' => 'Aktywny',
        'inactive' => 'Związek nieaktywny',
        'active_info' => 'Aktywne związki są widoczne w naszej aplikacji, dzięki czemu możesz z nich korzystać w zamówieniach, raportach i filtrach. Ukryjemy nieaktywne wpisy, natomiast dalej będą dostępne dla archiwalnych raportów i zamówień.',
    ],
    'unitTypes' => [
        'label' => 'Jednostka',
        'null' => '',
        'null_short' => '',
        'piece' => 'sztuka',
        'piece_short' => 'szt.',
        'set' => 'komplet',
        'set_short' => 'kpl.',
    ],
    'shipment' => [
        'cost' => 'Koszt wysyłki',
        'payment_type' => 'Typ płatności',
        'payment_type_info' => 'Informacja o typie płatności pozwoli nam połączyć wysyłki z fakturami',
        'cannotDeleteInfo' => 'Dla tej wysyłki istnieją już zamówienia w naszym systemie, nie można jej więc usunąć. Jeżeli chcesz ją ukryć z dostępnych wysyłek, zaznacz przesyłkę jako nieaktywną.',
    ],
    'paymentTypes' => [
        'title' => 'Sposób zapłaty',
        'null' => '--',
        'cash' => 'Gotówka',
        'cash_on_delivery' => 'Pobranie',
        'transfer' => 'Przelew',
        'card' => 'Karta',
    ],
    'orderNumberingTypes' => [
        'null' => '--',
        'monthly' => 'Miesięczny',
        'yearly' => 'Roczny',
    ],
    'settings' => [
        'general' => [
            'title' => 'Ustawienia ogólne',
            'subtitle' => 'Ogólne ustawienia dla modułu zamówień.',
            'order_numbering_format' => 'Format numerowania zamówienień',
        ],
    ],
    'icons' => [
        'createdToday' => 'Dodane dzisiaj o :date',
        'oneOfCreatedToday' => 'Jedna z przesyłek została dodana dzisiaj o :date',
        'multipack' => [
            'label' => 'Multipaczka dla :count wysyłek',
            'confirmedByAll' => 'Wszystkie zgrupowane wysyłki są potwierdzone przez klienta',
            'notConfirmed' => 'Jedna lub więcej wysyłek w grupie nie została potwierdzona przez klienta',
            'allConfirmedByUnion' => 'Wszystkie zgrupowane wysyłki są potwierdzone przez związek',
            'notAllConfirmedByUnion' => 'Jedna lub więcej wysyłek w grupie nie została potwierdzona przez związek',
            'shipmentNumber' => 'Numery wysyłek:',
            'invoiceNumbers' => 'Numery faktur:',
        ],
        'isPaid' => [
            'onePaid' => 'Zamówienie opłacone',
            'oneNotPaid' => 'Zamówienie nieopłacone',
            'allPaid' => 'Wszystkie wysyłki opłacone',
            'allNotPaid' => 'Jedna lub więcej wysyłek nie została opłacona',
        ],
    ],
    'export' => [
        'fileName' => 'wysylki_na_dzien_',
        'generated' => 'wygenerowane_',
        'btnTooltip' => 'Pobierz podsumowanie w pliku Excel',
        'sheets' => [
            'general' => 'Wysyłki',
        ],
        'type' => [
            'label' => 'Typ zamówienia',
            'refunded' => 'Refundowane',
            'private' => 'Prywatne',
        ],
        'ups' => [
            'first_name' => 'Imie',
            'last_name' => 'Nazwisko',
            'street' => 'ulica',
            'postal_code' => 'kod',
            'city' => 'miejscowosc',
            'phone' => 'tel',
            'email' => 'mail1',
            'is_cash_on_delivery' => 'POBRANIE',
            'cash_on_delivery_amount' => 'KWOTA',
        ],
    ],
    'analytics' => [
        'page' => [
            'title' => 'Analityka dla zamówień',
            'subtitle' => 'Poniżej możesz znaleźć podsumowania i dane analityczne Twoich zamówień. Napisz do nas jeżeli masz pomysł na dodanie brakujących statystyk na tej stronie.',
        ],
        'cards' => [
            'counts' => [
                'title' => 'Liczby wysyłek',
                'all' => 'łącznie (razem z anulowanymi)',
                'open' => '{0} aktywnych| {1} aktywna|[2,4] aktywne|[5,*] aktywnych',
                'open_without_shipment_date' => '{0} aktywnych (bez ustalonej daty wysyłki)| {1} aktywna (bez ustalonej daty wysyłki)|[2,4] aktywne (bez ustalonej daty wysyłki)|[5,*] aktywnych (bez ustalonej daty wysyłki)',
                'prepared' => '{0} przygotowanych do wysyłki|{1} przygotowana do wysyłki|[2,4] przygotowane do wysyłki|[5,*] przygotowanych do wysyłki',
                'completed' => '{0} skompletowanych|{1} skompletowana|[2,4] skompletowane|[5,*] skompletowanych',
                'paid' => '[0,4] oznaczone jako opłacone|[5,*] oznaczonych jako opłacone',
                'cancelled' => '{0} anulowanych|{1} anulowana|[2,4] anulowane|[5,*] anulowanych',
                'private' => '{0} prywatnych|{1} prywatna|[2,4] prywatne|[5,*] prywatnych',
                'refunded' => '{0} refundowanych|{1} refundowana|[2,4] refundowane|[5,*] refundowanych',
            ],
            'sums' => [
                'title' => 'Wartości wysyłek',
                'all' => 'łącznie (bez anulowanych)',
            ],
            'productCounts' => [
                'title' => 'Zamówione produkty',
                'subtitle' => 'Poniżej możesz przejrzeć podsumowanie zamówionych produktów wraz z informacją o stosunku wysłanych do wszystkich.',
            ],
        ],
        'wip' => [
            'title' => "Budujemy tą stronę dla Ciebie!",
            'subtitle' => "Tylko Ty wiesz jakie dane mogą być dla Ciebie interesujące! Daj nam znać czego tutaj brakuje.",
            'whatsapp' => "Napisz do nas na whatsapp",
            'email' => "Skontaktuj się przez e-mail",
            'emailSubject' => "Chcę zobaczyć coś nowego na stronie analityki zamówień",
        ],
    ],
    'daily' => [
        'forgotten' => [
            'title' => 'Nie zapomnij o nas!',
            'subtitle' => "Poniżej znajdziesz listę niewysłanych przesyłek z poprzednich dni. Przejrzyj listę i uaktualnij zamówienia aby odzwierciedlić aktualny stan.",
        ]
    ],
];
