<?php
return [
    'mainPageTitle' => 'Lista zamówień',
    'mainPageSubtitle' => 'Możesz zarządzać swoimi zamówieniami. Zamówienia usunięte lub zakończone są widoczne na osobnej liście.',
    'clientsPageTitle' => 'Twoi klienci',
    'clientsPageSubtitle' => 'Na tej stronie możesz zarządzać danymi Twoich klientów. Każdy z dodanych klientów będzie dostępny również w sekcji zamówień.',
    'shipmentPageTitle' => 'Wysyłki',
    'shipmentPageSubtitle' => 'Na tej stronie możesz zarządzać wysyłkami do Twoich zamówień. ',
    'settingsPageTitle' => 'Ustawienia sklepu',
    'settingsPageSubtitle' => 'Na tej stronie możesz zmieniać ustawienia modułu zamówień. Możesz zarządzać swoim produktami, listą związków pszczelarskich oraz metodami wysyłki.',
    'statsPageTitle' => 'Statystyki zamówień',
    'statsPageSubtitle' => 'Możesz tu sprawdzić statystyki zamówień',
    'settingsProductTitle' => 'Produkty',
    'settingsClubsTitle' => 'Koła pszczelarskie',
    'settingsUnionsTitle' => 'Związki pszczelarskie',
    'settingsUnionsSingleTitle' => 'Związek pszczelarski',
    'settingsShippingTitle' => 'Metody wysyłki',
    'defaultLabel' => 'Domyślna',
    'shipmentNameLabel' => 'Nazwa',
    'shipmentPriceLabel' => 'Koszt',
    'shipmentIsFreeLabel' => 'Darmowa wysyłka',
    'shipmentDateLabel' => 'Data wysyłki',
    'shipmentDateShortLabel' => 'Data',
    'deleteShipmentTooltip' => 'Usuń metodę wysyłki',
    'shipmentAddedSuccessMessage' => 'Pomyślnie dodano metodę wysyłki',
    'shipmentsDeleteSuccessMessage' => 'Pomyślnie usunięto metodę wysyłki',
    'shipmentUpdateSuccessMessage' => 'Pomyślnie zmieniono metodę wysyłki',
    'addNewShipmentMethodBtnLabel' => 'Dodaj nową metodę wysyłki',
    'saveOrderSuccessMessage' => 'Zamówienie zostało zapisane',
    'cancelOrderSuccessMessage' => 'Zamówienie zostało anulowane',
    'addNewClubBtnLabel' => 'Dodaj nowe koło',
    'addNewUnionBtnLabel' => 'Dodaj nowy związek',
    'editUnionBtnLabel' => 'Edytuj dane związku',
    'clubEmailLabel' => 'Adres email koła',
    'unionEmailLabel' => 'Adres email związku',
    'clubNameLabel' => 'Nazwa koła',
    'unionNameLabel' => 'Nazwa związku',
    'deleteClubTooltip' => 'Usuń koło pszczelarskie',
    'deleteUnionTooltip' => 'Usuń związek pszczelarski',
    'clubAddedSuccessMessage' => 'Pomyślnie dodano koło pszczelarskie',
    'unionAddedSuccessMessage' => 'Pomyślnie dodano związek pszczelarski',
    'clubsDeleteSuccessMessage' => 'Pomyślnie usunięto koło pszczelarskie',
    'unionsDeleteSuccessMessage' => 'Pomyślnie usunięto związek pszczelarski',
    'clubUpdateSuccessMessage' => 'Pomyślnie zmieniono koło pszczelarskie',
    'unionUpdateSuccessMessage' => 'Pomyślnie zmieniono związek pszczelarski',
    'clubsCardSubtitle' => 'Lista kół pszczelarskich będzie wykorzystana w przypadku zamówień refundowanych. Możesz wprowadzić adres email aby wysyłać raporty bezpośrednio na adres koła.',
    'unionsCardSubtitle' => 'Lista związków pszczelarskich będzie wykorzystana w przypadku zamówień rozliczanych przez związki. Możesz wprowadzić adres email aby wysyłać raporty bezpośrednio na adres związku.',
    'unions404Subtitle' => 'Lista związków pszczelarskich jest pusta, możesz dodać pierwszy wpis klikając w przycisk w prawym dolnym rogu.',
    'shipmentCardSubtitle' => 'Możesz zdefiniować wiele metod wysyłki, które później będą użyte przy tworzeniu zamówienia. Dla przykładu metodą wysyłki może być klasyczna paczka lub odbiór osobisty w wybranej lokalizacji.',
    'productNameLabel' => 'Nazwa',
    'productCodeLabel' => 'Kod produktu',
    'productRegularPriceLabel' => 'Cena',
    'productBulkPriceLabel' => 'Cena hurtowa',
    'productPriceShortLabel' => 'Cena',
    'productSumShortLabel' => 'Suma',
    'productTypeLabel' => 'Kategoria',
    'productTypeQueen' => 'Matka',
    'productTypeOther' => 'Inne',
    'settingsProductsTitle' => 'Twoje produkty',
    'productsCardSubtitle' => 'Możesz zdefiniować wiele produktów w Twojej pasiece, będą one dostępne do wyboru na karcie zamówienia',
    'deleteProductTooltip' => 'Usuń produkt',
    'addNewProductBtnLabel' => 'Dodaj produkt',
    'defineNewProductBtnLabel' => 'Stwórz nowy produkt',
    'productAddedSuccessMessage' => 'Pomyślnie dodano produkt',
    'productsDeleteSuccessMessage' => 'Pomyślnie usunięto produkt',
    'productUpdateSuccessMessage' => 'Pomyślnie zmieniono dane produktu',
    'clientDisplayNameLabel' => 'Imię i nazwisko',
    'clientFirstNameLabel' => 'Imię',
    'clientLastNameLabel' => 'Nazwisko',
    'clientPhoneLabel' => 'Telefon',
    'clientPhoneShortLabel' => 'Tel',
    'clientEmailLabel' => 'E-mail',
    'clientAddressLabel' => 'Adres',
    'clientsDeleteSuccessMessage' => 'Pomyślnie usunięto klienta z aplikacji',
    'clientsCreatedSuccessMessage' => 'Pomyślnie dodano klienta',
    'clientsUpdatedSuccessMessage' => 'Pomyślnie edytowane dane klienta',
    'fabAddClientTooltip' => 'Dodaj nowego klienta',
    'fabClientEditTitle' => 'Edytuj dane klienta',
    'fabClientChangeTitle' => 'Dodaj i zastąp klienta',
    'clientBasicDataTitle' => 'Podstawowe dane',
    'clientAddressDataTitle' => 'Dane adresowe do wysyłki',
    'inputAddressStreetLabel' => 'Ulica \ Miejscowość',
    'inputAddressBuildingNumberLabel' => 'Numer domu',
    'inputAddressApartmentNumberLabel' => 'Numer mieszkania',
    'inputAddressPostCodeLabel' => 'Kod pocztowy',
    'inputAddressCityLabel' => 'Miasto \ Poczta',
    'searchByLabel' => 'Szukaj wśród klientów',
    'searchOrdersByLabel' => 'Szukaj w zamówieniach',
    'searchShipmentsByLabel' => 'Szukaj w wysyłkach',
    'searchOrdersHintLabel' => 'Możesz szukać po numerze zamówienia, nazwisku klienta, numerze telefonu, adresie email lub nazwie koła pszczelarskiego',
    'clientOrderClubLabel' => 'Związek pszczelarski klienta',
    'clientOrderClubLabelShort' => 'Koło pszczelarskie',
    'clientOrderClubLabelSuperShort' => 'Koło',
    'clientOrderUnionLabelShort' => 'Związek',
    'clientOrderUnionLabelSuperShort' => 'Związek',
    'clientCommentLabel' => 'Komentarz',
    'clientWarningLabel' => 'Status współpracy',
    'clientAdditionalDataTitle' => 'Dodatkowe dane klienta',
    'clientCommentsTitle' => 'Informacje o współpracy z klientem',
    'clientCooperationNullLabel' => 'Brak uwag',
    'clientCooperationWarningLabel' => 'Ostrzeżenie',
    'clientCooperationBlockListLabel' => 'Czarna lista',
    'notes' => 'Notatki',

    // Orders
    'fabAddOrderTooltip' => 'Dodaj nowe zamówienie',
    'detailsPageTitle' => 'Zamówienie',
    '404Subtitle' => 'Nie znaleźliśmy tego zamówienia w naszym systemie',
    'detailsPageBackBtnLabel' => 'Lista zamówień',
    'lastUpdatedLabel' => 'Ostatnia aktualizacja',
    'createdLabel' => 'Utworzone',
    'createdAtLabel' => 'Data złożenia zamówienia',
    'client' => [
        'cardTitle' => 'Główny klient',
    ],
    'productsDataTitle' => 'Produkty',
    'shipmentsDataTitle' => 'Wysyłka',
    'shipmentsDayTitle' => 'Wysyłka',
    'refundDetailsDataTitle' => 'Dane do refundacji',
    'shipmentDetailsDataTitle' => 'Szczegóły wysyłki',
    'orderDataTitle' => 'Szczegóły zamówienia',
    'orderTypeLabel' => 'Zamówienie refundowane',
    'orderTypeShortLabel' => 'Refundacja',
    'source' => [
        'label' => 'Źródło zamówienia',
        'phone' => 'Telefon',
        'mail' => 'E-mail',
        'direct' => 'Bezpośrednie',
        'other' => 'Inne',
    ],
    'orderCommentLabel' => 'Komentarz',
    'orderIsBulkLabel' => 'Zamówienie hurtowe',
    'orderIsConfirmedByClientLabel' => 'Wysyłka potwierdzona',
    'orderIsConfirmedByClientShortLabel' => 'Potwierdzenie',
    'orderIsNotConfirmedByClientLabel' => 'Wysyłka niepotwierdzona',
    'orderIsRefundConfirmedLabel' => 'Refundacja potwierdzona',
    'orderIsRefundNonConfirmedLabel' => 'Refundacja niepotwierdzona',
    'ordersDeleteSuccessMessage' => 'Zamówienie zostało usunięte',
    'shipmentConfirmedSuccessfully' => 'Wysyłka została potwierdzona',
    'updateSuccessMessage' => 'Pomyślnie zapisaliśmy zmiany.',
    'priceSummaryLabel' => 'Razem',
    'confirmBtnLabel' => 'Potwierdź',
    'shipmentDateChangedSuccessfully' => 'Data wysyłki została zmieniona',
    'disableRefundLabel' => 'Wyłącz refundację',
    'enableRefundLabel' => 'Włącz refundację',
    'duplicateOrderLabel' => 'Duplikuj',

    //order status
    'statusHeadline' => 'Status',
    'refundHeadline' => 'Refundacja',
    'status_null' => '--',
    'status_draft' => 'Szkic',
    'status_new' => 'Nowe',
    'status_confirmed' => 'Potwierdzona',
    'status_unconfirmed' => 'Niepotwierdzona',
    'status_completed' => 'Zrealizowane',
    'status_sent' => 'Wysłane',
    'status_cancelled' => 'Anulowane',
    'status_prepared' => 'Spakowane',
    'status_ready' => 'Przygotowane',
    'status_active' => 'Aktywne',
    'status_paid' => 'Zapłacone',
    'status_all' => 'Wszystkie',
    'cancelBtnLabel' => 'Anuluj zamówienie',

    //Client details
    'clientLabel' => 'Klient',
    'clientPayingLabel' => 'Płatnik',
    'queenReceiverLabel' => 'Odbiorca na rozliczeniu',
    'invoiceLabel' => 'Rozliczenia',
    'clientSearchPlaceholder' => 'Zacznij pisać aby wyszukać klienta',
    'clubSearchPlaceholder' => 'Zacznij pisać aby wyszukać koło',
    'noDataForClientSearch' => 'Brak wyników',

    //Product detals
    'productLabel' => 'Produkt',
    'productSearchPlaceholder' => 'Zacznij pisać aby wyszukać produkt',
    'productCountLabel' => 'Ilość',
    'showAdvancedBtnLabel' => 'Zaawansowane',
    'productRefundedLabel' => 'Produkt refundowany',
    'advancedSettingsTitle' => 'Zaawansowane ustawienia produktu',
    'otherDataTitle' => 'Przyjęcie zamówienia',
    'unionSearchPlaceholder' => 'Zacznij pisać, żeby wyszukać związek',
    'noDateSetLabel' => 'Brak daty',

    //Queen Types
    'productQueenTypeLabel' => 'Powiązanie typu matki w systemie',
    'productQueenTypeShortLabel' => 'Typ matki',
    'productQueenType_null' => '--',
    'productQueenType_nu' => 'Nieunasieniona',
    'productQueenType_un' => 'Unasieniona naturalnie',
    'productQueenType_us' => 'Unasieniona sztucznie',
    'productQueenType_uss' => 'Unasieniona sztucznie z potwierdzonym czerwieniem',
    'productQueenType_nucs' => 'Odkład',

    //Shipments
    'addNewShipmentBtnLabel' => 'Dodaj nową wysyłkę',
    'deleteShipmentSuccessMessage' => 'Wysyłka została usunięta',
    'addShipmentSuccessMessage' => 'Wysyłka została dodana',
    'showClientInformation' => 'Zmień klienta',
    'shipmentClientLabel' => 'Odbiorca przesyłki',
    'shipmentClientShortLabel' => 'Odbiorca',
    'shipmentSentLabel' => 'Wysłane',
    'shipmentWaitingLabel' => 'Oczekuje',
    'shipmentSentLongLabel' => 'Zamówienie wysłane',
    'shipmentPreparedLabel' => 'Przygotowane',
    'shipmentPreparedLongLabel' => 'Zamówienie przygotowane',
    'shipmentBasketLabel' => 'Produkty',
    'shipmentValueLabel' => 'Wartość',
    'shipmentSeeDetailsBtnLabel' => 'Przejdź do zamówienia',
    'shipmentMethodLabel' => 'Metoda',
    'shipmentNoDateTitle' => 'Wysyłki bez ustawionej daty',
    'shipmentTypeLabel' => 'Typ wysyłki',
    'isShipmentNumberGeneratedLabel' => 'Wygenerowano dokument wysyłki',
    'shipmentNumberLabel' => 'Numer przewozowy',

    //Client company data
    'clientCompanyDataTitle' => 'Dane firmy klienta',
    'inputCompanyAddressLabel' => 'Adres',
    'inputCompanyTaxNumberLabel' => 'Główny numer podatkowy',
    'inputCompanyNameLabel' => 'Pełna nazwa firmy',
    'inputCompanyPostCodeLabel' => 'Kod pocztowy',
    'inputCompanyCityLabel' => 'Miasto',
    'maskHint' => 'Wpisz bez myślników i spacji',

    //Shipment date proposition
    'shipmentDatePropTitle' => 'Wybierz datę wysyłki',
    'shipmentDatePropShortTitle' => 'Zmień datę',
    'chooseBtnLabel' => 'Zapisz wybór',
    'chooseBtnTooltip' => 'Wybrany dzień',
    'selectBtnLabel' => 'Zaznacz dzień',
    'todayBtnLabel' => 'Dzisiaj',
    'nextPeriodBtnLabel' => 'Następny miesiąc',
    'prevPeriodBtnLabel' => 'Poprzedni miesiąc',
    'addProductsToSeeLabel' => 'Dodaj produkty, aby wybrać datę',
    'collapseShipmentDayCard' => 'Zwiń szczegóły',
    'expandShipmentDayCard' => 'Rozwiń szczegóły',
    'prognosedLimitWarning' => 'Istnieje ryzyko przekroczenia prognozowanej ilości zamówionych matek!',
    'prognosedLabel' => 'Prognozowane',
    'orderedLabel' => 'Zamówione',
    'differenceLabel' => 'Różnica',

    //Queen insemination statuses
    'queen_vq' => 'NU',
    'queen_mq' => 'UN',
    'queen_ai' => 'US',
    'queen_aib' => 'USS',

    //Warnings
    'warning_headline' => 'Dane klienta niekompletne',
    'warning_noClient' => 'Brak wybranego klienta',
    'warning_noPhone' => 'brak telefonu klienta',
    'warning_noAddressData' => 'niepełne dane adresowe',

    //Invoice panel
    'invoicePreparedLabel' => 'Faktura wystawiona dla wysyłki',

    'table' => [
        'seasonHint' => 'od :startDate do :endDate',
        'numberLabel' => 'Numer',
        'statusLabel' => 'Status',
        'clientDisplayNameLabel' => 'Klient',
        'goToOrderBtnLabel' => 'Przejdź do zamówienia',
        'progressLabel' => 'Stopień realizacji',
        'seasonNullLabel' => 'Sezon: --',
        '404Subtitle' => 'Nie znaleźliśmy żadnych zamówień dla Twojej pasieki. Aby rozpocząć, dodaj pierwsze zamówienie używając przycisku w dolnym prawym rogu.',
        '404OrderTableSubtitle' => 'Nie znaleźliśmy żadnych wysyłek. Aby rozpocząć, dodaj pierwszą wysyłkę.',
        'queenLineLabel' => 'Linia',
        'shipment' => [
            'settingsLabel' => 'Szczegóły wysyłki',
            'documentsLabel' => 'Dokumenty wysyłki',
        ],
        '404NoShipmentForThisDay' => 'Na dzisiaj nie zaplanowano żadnych wysyłek.',
        'but' => 'lub',
        'goToOrders' => 'Przejdź do zamówień',
        'noProductsInOrder' => 'Brak produktów w zamówieniu',
    ],
    'child' => [
        'otherLabel' => 'Inne',
    ],
    'queenTypes' => [
        'nu' => 'NU',
        'un' => 'UN',
        'us' => 'US',
        'uss' => 'USS',
        'nucs' => 'Odkład',
    ],
    'files' => [
        'emptyTitle' => 'Dodaj pliki',
        'title' => 'Dołączone pliki (:value)',
        'addFile' => 'Dodaj nowy plik',
    ],
];
