<?php
return [
    'pageTitle' => 'Serie matek',
    'pageSubtitle' => 'Serie matek mogą być wykorzystywane do lepszego planowania pojawiania się nowych matek w perspektywie czasu.',
    'addSuccessMessage' => 'Nowa seria została pomyślnie dodana!',
    'deleteSuccessMessage' => 'Seria :name została pomyślnie usunięta.',
    'updateSuccessMessage' => 'Seria :name została pomyślnie uaktualniona.',
    'transferredAtLabel' => 'Data przełożenia larw',
    'joinedAtLabel' => 'Data komasacji',
    'isolatedAtLabel' => 'Data izolacji',
    'bornAtLabel' => 'Data wygryzienia',
    'serieMaxCountLabel' => 'Spodziewana ilość matek',
    'fabAddNewSerieTooltip' => 'Dodaj nową serię',
    'newSerieInfoTitle' => 'Do czego służą serie w aplikacji?',
    'newSerieInfoDesc' => 'Dzięki seriom możesz lepiej zaplanować czynności od przenoszenia larw aż po wygryzanie się matek w inkubatorze. Serie są porównywane z prognozami sprzedażych przychodzącymi z zamówień klientów, dając Ci pogląd na to jak wiele zamówień możesz obsłużyć w danym okresie sezonu.',
    'serieNameLabel' => 'Nazwa serii',
    'manualEfficiencyLabel' => 'Używaj domyślnych wydajności',
    'editSerieModalTitle' => 'Edytuj serię',
    'startDateLabel' => 'Data startu sezonu',
    'endDateLabel' => 'Data końca sezonu',
    'addMultipleSerieSuccessMessage' => 'Pomyślnie dodano wiele serii',
    'addMultipleSeriesModalHivesPrefixLabel' => 'Prefiks nazwy serii',
    'addMultipleSeriesModalTitle' => 'Dodaj wiele serii',
    'addMultipleSeriesModalInfoBoxTitle' => 'Podgląd tworzonych serii',
    'noHivesInfoBox' => 'Wypełnij daty startu i końca sezonu oraz nazwę, żeby zobaczyć przykłady tworzonych serii.',
    'saveOnlyThisSerieLabel' => 'Zmień tylko tę serię',
    'saveAllSeriesThisLabel' => 'Zmień również kolejne serie z listy',
    'revealSerieTitle' => 'Lista serii',
    'revealSerieSubtitle' => 'Ta seria została stworzona w zestawie z innymi seriami. Czy chcesz zmienić również daty kolejnych serii z zestawu?',
    'defaultEfficiencyInfo' => 'Domyślnie serie korzystają z dynamicznej kalulacji skuteczności poszczególnych kroków. Jeżeli chcesz wymusić użycie domyślnych wartości, zaznacz tą opcję.',

    //Statistics
    'lostBornCountLabel' => 'Ilość utraconych przy wygryzaniu',
    'joinedCountLabel' => 'Ilość skomasowanych',
    'isolatedCountLabel' => 'Ilość zaizolowanych',
    'transferredCountLabel' => 'Ilość przełożonych larw',
    'realCountLabel' => 'Rzeczywista ilość matek wygryzionych',
    'prognosedCountLabel' => 'Prognozowana ilość matek wygryzionych',
    'efficiencyLabel' => 'Skuteczność',
    'efficiencyJoinedLabel' => 'Skuteczność przyjęć',

    'workCardTitle' => 'Serie matek pszczelich',
    'workCardInfoTitle' => 'Do czego służy ten panel?',
    'workCardSubTitle' => 'Jeżeli korzystasz z funkcjonalności serii matek pszczelich, w tej sekcji znajdą się serie, które w danym dniu będą wymagały akcji z Twojej strony. Wprowadzone dane będą używane do prognozowania ilości dostępnych matek.',
    'day_transferred' => 'Dzień przekładania larw',
    'day_joined' => 'Dzień komasacji',
    'day_isolated' => 'Dzień izolowania',
    'day_born' => 'Dzień wygryzania',
    'allGoodText' => 'Wszystko w porządku! Na dzisiaj nie ma tutaj zadań lub wszystkie zadania zostały wykonane.',

];
