<?php
return [
    'accountAppName' => 'Konto',
    'apiaryAppName' => 'Moja Pasieka',
    'clubAppName' => 'Klub',
    'queensAppName' => 'Hodowcy Matek',
    'logoutBtnLabel' => 'Wyloguj',
    'createdBy' => 'Stworzone przez',
    'createdAt' => 'Utworzono',
    'workInProgessHeadline' => 'Pracujemy nad tą sekcją!',
    'workInProgessSubheadline' => 'Nasze pszczółki pracują nad wprowadzeniem ulepszeń w tym miejscu. Wróć niedługo, żeby zobaczyć co się zmieniło!',
    'placeholderTitle' => 'Przykładowy tytuł',
    'cancelBtnLabel' => 'Anuluj',
    'closeBtnLabel' => 'Zamknij',
    'saveBtnLabel' => 'Zapisz',
    'addBtnLabel' => 'Dodaj',
    'deleteBtnLabel' => 'Usuń',
    'printBtnLabel' => 'Drukuj',
    'filterBtnLabel' => 'Filtruj',
    'confirm' => 'Potwierdź:',
    'search' => 'Szukaj',
    'goBack' => 'Wróć',
    'new' => 'Nowy',
    'owner' => 'Założyciel',
    'noResults' => 'Brak wyników',
    'noResultsForSelectedDay' => 'Nie mamy jeszcze danych dla wybranego dnia.',
    'partnerPszczelarzaURI' => 'https://partnerpszczelarza.pl',
    'today' => 'dzisiaj',
    'loadingDataMsg' => 'Ładujemy dane dla Ciebie...',
    'continueBtnLabel' => 'Przejdź dalej',
    'savencontinueBtnLabel' => 'Zapisz i kontynuuj',
    'detailsBtnLabel' => 'Szczegóły',
    'editBtnLabel' => 'Edytuj',
    'moveBtnLabel' => 'Przenieś',
    'showBtnLabel' => 'Zobacz',
    'errorOccurredMessage' => 'W trakcie wykonywania tej akcji wystąpił błąd. Spróbuj ponownie.',
    'getBackToHomepageBtnLabel' => 'Wróć na stronę główną',
    '401AltTitle' => 'Brak dostępu!',
    '401Title' => 'Ups!',
    '401Subtitle' => 'Wygląda na to, że nie masz uprawnień do tej strony. <br/>Jeśli uważasz, że tak nie powinno być, skontaktuj się z właścicielem pasieki.',
    'onLabel' => 'Włączone',
    'offLabel' => 'Wyłączone',
    'archiveBtnLabel' => 'Archiwizuj',
    '404Title' => 'Pusto tu!',
    '404Subtitle' => 'Nie znaleźliśmy nic do wyświetlenia.',
    'undefinedLabel' => 'Brak',
    'scrollToTopLabel' => 'Wróć na górę',
    'dataTable' => [
        'allOptionLabel' => 'Wszystkie',
        'rowsPerPageLabel' => 'Ilość wyników',
        'pageText' => '{0}-{1} z {2}',
    ],
    'accept' => 'Zaakceptuj',
    'reject' => 'Odrzuć',
    'true' => 'Tak',
    'false' => 'Nie',
    'copy' => '-kopia',
    'uploadBtn' => 'Prześlij',
    'chooseBtn' => 'Wybierz',
    'downloadBtn' => 'Pobierz',
    'optionalFields' => 'Pola opcjonalne',
    'goToSubscriptionPageBtn' => 'Ulepsz swoje konto',
    'actionsLabel' => 'Akcje',
    'orText' => 'lub',
    'links' => [
        'documentation' => [
            'text' => 'Dokumentacja',
            'href' => 'https://partnerpszczelarza.pl/aplikacja-hodowcy/dokumentacja/',
        ],
        'privacyPolicy' => [
            'text' => 'Polityka Prywatności',
            'href' => 'https://partnerpszczelarza.pl/polityka-prywatnosci',
        ],
    ],
    'refreshBtn' => 'Odśwież',

    // time
    'today' => 'dzisiaj',
    'thisWeek' => 'w tym tygodniu',
    'thisMonth' => 'w tym miesiącu',
    'thisYear' => 'w tym roku',
    'customDateRange' => 'własny zakres',
    'from' => 'od',
    'to' => 'do',
    'dataTable' => [
        'allOptionLabel' => 'Wszystkie',
        'rowsPerPageLabel' => 'Ilość wyników',
        'pageText' => '{0}-{1} z {2}',
    ],
];
